using System.Collections.Generic;

namespace PlayfulSparkle
{
    /// <summary>
    /// The <c>DefaultMappings</c> class provides a collection of default character mappings or representations.
    /// </summary>
    internal class DefaultMappings
    {
        /// <summary>
        /// A static dictionary that stores 1818 default character mappings as key-value pairs.
        /// Both keys and values are strings. The dictionary uses ordinal string comparison,
        /// meaning comparisons are case-sensitive and based on the Unicode code points of the characters.
        /// </summary>
        public static Dictionary<int[], string> chars = new Dictionary<int[], string>()
        {
            // Latin
            { new int[] { 0xC0 }, "A"}, // À
            { new int[] { 0xC1 }, "A"}, // Á
            { new int[] { 0xC2 }, "A"}, // Â
            { new int[] { 0xC3 }, "A"}, // Ã
            { new int[] { 0xC4 }, "Ae"}, // Ä
            { new int[] { 0xC5 }, "A"}, // Å
            { new int[] { 0xC6 }, "AE"}, // Æ
            { new int[] { 0xC7 }, "C"}, // Ç
            { new int[] { 0xC8 }, "E"}, // È
            { new int[] { 0xC9 }, "E"}, // É
            { new int[] { 0xCA }, "E"}, // Ê
            { new int[] { 0xCB }, "E"}, // Ë
            { new int[] { 0xCC }, "I"}, // Ì
            { new int[] { 0xCD }, "I"}, // Í
            { new int[] { 0xCE }, "I"}, // Î
            { new int[] { 0xCF }, "I"}, // Ï
            { new int[] { 0xD0 }, "D"}, // Ð
            { new int[] { 0xD1 }, "N"}, // Ñ
            { new int[] { 0xD2 }, "O"}, // Ò
            { new int[] { 0xD3 }, "O"}, // Ó
            { new int[] { 0xD4 }, "O"}, // Ô
            { new int[] { 0xD5 }, "O"}, // Õ
            { new int[] { 0xD6 }, "Oe"}, // Ö
            { new int[] { 0x150 }, "O"}, // Ő
            { new int[] { 0xD8 }, "O"}, // Ø
            { new int[] { 0xD9 }, "U"}, // Ù
            { new int[] { 0xDA }, "U"}, // Ú
            { new int[] { 0xDB }, "U"}, // Û
            { new int[] { 0xDC }, "Ue"}, // Ü
            { new int[] { 0x170 }, "U"}, // Ű
            { new int[] { 0xDD }, "Y"}, // Ý
            { new int[] { 0xDE }, "TH"}, // Þ
            { new int[] { 0xDF }, "ss"}, // ß
            { new int[] { 0xE0 }, "a"}, // à
            { new int[] { 0xE1 }, "a"}, // á
            { new int[] { 0xE2 }, "a"}, // â
            { new int[] { 0xE3 }, "a"}, // ã
            { new int[] { 0xE4 }, "ae"}, // ä
            { new int[] { 0xE5 }, "a"}, // å
            { new int[] { 0xE6 }, "ae"}, // æ
            { new int[] { 0xE7 }, "c"}, // ç
            { new int[] { 0xE8 }, "e"}, // è
            { new int[] { 0xE9 }, "e"}, // é
            { new int[] { 0xEA }, "e"}, // ê
            { new int[] { 0xEB }, "e"}, // ë
            { new int[] { 0xEC }, "i"}, // ì
            { new int[] { 0xED }, "i"}, // í
            { new int[] { 0xEE }, "i"}, // î
            { new int[] { 0xEF }, "i"}, // ï
            { new int[] { 0xF0 }, "d"}, // ð
            { new int[] { 0xF1 }, "n"}, // ñ
            { new int[] { 0xF2 }, "o"}, // ò
            { new int[] { 0xF3 }, "o"}, // ó
            { new int[] { 0xF4 }, "o"}, // ô
            { new int[] { 0xF5 }, "o"}, // õ
            { new int[] { 0xF6 }, "oe"}, // ö
            { new int[] { 0x151 }, "o"}, // ő
            { new int[] { 0xF8 }, "o"}, // ø
            { new int[] { 0xF9 }, "u"}, // ù
            { new int[] { 0xFA }, "u"}, // ú
            { new int[] { 0xFB }, "u"}, // û
            { new int[] { 0xFC }, "ue"}, // ü
            { new int[] { 0x171 }, "u"}, // ű
            { new int[] { 0xFD }, "y"}, // ý
            { new int[] { 0xFE }, "th"}, // þ
            { new int[] { 0xFF }, "y"}, // ÿ
            { new int[] { 0x1E9E }, "SS"}, // ẞ

            // Vietnamese
            { new int[] { 0x110 }, "D"}, // Đ
            { new int[] { 0x111 }, "d"}, // đ
            { new int[] { 0x129 }, "i"}, // ĩ
            { new int[] { 0x128 }, "I"}, // Ĩ
            { new int[] { 0x169 }, "u"}, // ũ
            { new int[] { 0x168 }, "U"}, // Ũ
            { new int[] { 0x1A1 }, "o"}, // ơ
            { new int[] { 0x1A0 }, "O"}, // Ơ
            { new int[] { 0x1B0 }, "u"}, // ư
            { new int[] { 0x1AF }, "U"}, // Ư
            { new int[] { 0x1EA1 }, "a"}, // ạ
            { new int[] { 0x1EA0 }, "A"}, // Ạ
            { new int[] { 0x1EA3 }, "a"}, // ả
            { new int[] { 0x1EA2 }, "A"}, // Ả
            { new int[] { 0x1EA5 }, "a"}, // ấ
            { new int[] { 0x1EA4 }, "A"}, // Ấ
            { new int[] { 0x1EA7 }, "a"}, // ầ
            { new int[] { 0x1EA6 }, "A"}, // Ầ
            { new int[] { 0x1EA9 }, "a"}, // ẩ
            { new int[] { 0x1EA8 }, "A"}, // Ẩ
            { new int[] { 0x1EAB }, "a"}, // ẫ
            { new int[] { 0x1EAA }, "A"}, // Ẫ
            { new int[] { 0x1EAD }, "a"}, // ậ
            { new int[] { 0x1EAC }, "A"}, // Ậ
            { new int[] { 0x1EAF }, "a"}, // ắ
            { new int[] { 0x1EAE }, "A"}, // Ắ
            { new int[] { 0x1EB1 }, "a"}, // ằ
            { new int[] { 0x1EB0 }, "A"}, // Ằ
            { new int[] { 0x1EB3 }, "a"}, // ẳ
            { new int[] { 0x1EB2 }, "A"}, // Ẳ
            { new int[] { 0x1EB5 }, "a"}, // ẵ
            { new int[] { 0x1EB4 }, "A"}, // Ẵ
            { new int[] { 0x1EB7 }, "a"}, // ặ
            { new int[] { 0x1EB6 }, "A"}, // Ặ
            { new int[] { 0x1EB9 }, "e"}, // ẹ
            { new int[] { 0x1EB8 }, "E"}, // Ẹ
            { new int[] { 0x1EBB }, "e"}, // ẻ
            { new int[] { 0x1EBA }, "E"}, // Ẻ
            { new int[] { 0x1EBD }, "e"}, // ẽ
            { new int[] { 0x1EBC }, "E"}, // Ẽ
            { new int[] { 0x1EBF }, "e"}, // ế
            { new int[] { 0x1EBE }, "E"}, // Ế
            { new int[] { 0x1EC1 }, "e"}, // ề
            { new int[] { 0x1EC0 }, "E"}, // Ề
            { new int[] { 0x1EC3 }, "e"}, // ể
            { new int[] { 0x1EC2 }, "E"}, // Ể
            { new int[] { 0x1EC5 }, "e"}, // ễ
            { new int[] { 0x1EC4 }, "E"}, // Ễ
            { new int[] { 0x1EC7 }, "e"}, // ệ
            { new int[] { 0x1EC6 }, "E"}, // Ệ
            { new int[] { 0x1EC9 }, "i"}, // ỉ
            { new int[] { 0x1EC8 }, "I"}, // Ỉ
            { new int[] { 0x1ECB }, "i"}, // ị
            { new int[] { 0x1ECA }, "I"}, // Ị
            { new int[] { 0x1ECD }, "o"}, // ọ
            { new int[] { 0x1ECC }, "O"}, // Ọ
            { new int[] { 0x1ECF }, "o"}, // ỏ
            { new int[] { 0x1ECE }, "O"}, // Ỏ
            { new int[] { 0x1ED1 }, "o"}, // ố
            { new int[] { 0x1ED0 }, "O"}, // Ố
            { new int[] { 0x1ED3 }, "o"}, // ồ
            { new int[] { 0x1ED2 }, "O"}, // Ồ
            { new int[] { 0x1ED5 }, "o"}, // ổ
            { new int[] { 0x1ED4 }, "O"}, // Ổ
            { new int[] { 0x1ED7 }, "o"}, // ỗ
            { new int[] { 0x1ED6 }, "O"}, // Ỗ
            { new int[] { 0x1ED9 }, "o"}, // ộ
            { new int[] { 0x1ED8 }, "O"}, // Ộ
            { new int[] { 0x1EDB }, "o"}, // ớ
            { new int[] { 0x1EDA }, "O"}, // Ớ
            { new int[] { 0x1EDD }, "o"}, // ờ
            { new int[] { 0x1EDC }, "O"}, // Ờ
            { new int[] { 0x1EDF }, "o"}, // ở
            { new int[] { 0x1EDE }, "O"}, // Ở
            { new int[] { 0x1EE1 }, "o"}, // ỡ
            { new int[] { 0x1EE0 }, "O"}, // Ỡ
            { new int[] { 0x1EE3 }, "o"}, // ợ
            { new int[] { 0x1EE2 }, "O"}, // Ợ
            { new int[] { 0x1EE5 }, "u"}, // ụ
            { new int[] { 0x1EE4 }, "U"}, // Ụ
            { new int[] { 0x1EE7 }, "u"}, // ủ
            { new int[] { 0x1EE6 }, "U"}, // Ủ
            { new int[] { 0x1EE9 }, "u"}, // ứ
            { new int[] { 0x1EE8 }, "U"}, // Ứ
            { new int[] { 0x1EEB }, "u"}, // ừ
            { new int[] { 0x1EEA }, "U"}, // Ừ
            { new int[] { 0x1EED }, "u"}, // ử
            { new int[] { 0x1EEC }, "U"}, // Ử
            { new int[] { 0x1EEF }, "u"}, // ữ
            { new int[] { 0x1EEE }, "U"}, // Ữ
            { new int[] { 0x1EF1 }, "u"}, // ự
            { new int[] { 0x1EF0 }, "U"}, // Ự
            { new int[] { 0x1EF3 }, "y"}, // ỳ
            { new int[] { 0x1EF2 }, "Y"}, // Ỳ
            { new int[] { 0x1EF5 }, "y"}, // ỵ
            { new int[] { 0x1EF4 }, "Y"}, // Ỵ
            { new int[] { 0x1EF7 }, "y"}, // ỷ
            { new int[] { 0x1EF6 }, "Y"}, // Ỷ
            { new int[] { 0x1EF9 }, "y"}, // ỹ
            { new int[] { 0x1EF8 }, "Y"}, // Ỹ

            // Arabic
            { new int[] { 0x621 }, "e"}, // ء
            { new int[] { 0x622 }, "a"}, // آ
            { new int[] { 0x623 }, "a"}, // أ
            { new int[] { 0x624 }, "w"}, // ؤ
            { new int[] { 0x625 }, "i"}, // إ
            { new int[] { 0x626 }, "y"}, // ئ
            { new int[] { 0x627 }, "a"}, // ا
            { new int[] { 0x628 }, "b"}, // ب
            { new int[] { 0x629 }, "t"}, // ة
            { new int[] { 0x62A }, "t"}, // ت
            { new int[] { 0x62B }, "th"}, // ث
            { new int[] { 0x62C }, "j"}, // ج
            { new int[] { 0x62D }, "h"}, // ح
            { new int[] { 0x62E }, "kh"}, // خ
            { new int[] { 0x62F }, "d"}, // د
            { new int[] { 0x630 }, "dh"}, // ذ
            { new int[] { 0x631 }, "r"}, // ر
            { new int[] { 0x632 }, "z"}, // ز
            { new int[] { 0x633 }, "s"}, // س
            { new int[] { 0x634 }, "sh"}, // ش
            { new int[] { 0x635 }, "s"}, // ص
            { new int[] { 0x636 }, "d"}, // ض
            { new int[] { 0x637 }, "t"}, // ط
            { new int[] { 0x638 }, "z"}, // ظ
            { new int[] { 0x639 }, "e"}, // ع
            { new int[] { 0x63A }, "gh"}, // غ
            { new int[] { 0x640 }, "_"}, // ـ
            { new int[] { 0x641 }, "f"}, // ف
            { new int[] { 0x642 }, "q"}, // ق
            { new int[] { 0x643 }, "k"}, // ك
            { new int[] { 0x644 }, "l"}, // ل
            { new int[] { 0x645 }, "m"}, // م
            { new int[] { 0x646 }, "n"}, // ن
            { new int[] { 0x647 }, "h"}, // ه
            { new int[] { 0x648 }, "w"}, // و
            { new int[] { 0x649 }, "a"}, // ى
            { new int[] { 0x64A }, "y"}, // ي
            { new int[] { 0x64E, 0x200E }, "a"}, // َ‎
            { new int[] { 0x64F }, "u"}, // ُ
            { new int[] { 0x650, 0x200E }, "i"}, // ِ‎
            { new int[] { 0x660 }, "0"}, // ٠
            { new int[] { 0x661 }, "1"}, // ١
            { new int[] { 0x662 }, "2"}, // ٢
            { new int[] { 0x663 }, "3"}, // ٣
            { new int[] { 0x664 }, "4"}, // ٤
            { new int[] { 0x665 }, "5"}, // ٥
            { new int[] { 0x666 }, "6"}, // ٦
            { new int[] { 0x667 }, "7"}, // ٧
            { new int[] { 0x668 }, "8"}, // ٨
            { new int[] { 0x669 }, "9"}, // ٩

            // Persian / Farsi
            { new int[] { 0x686 }, "ch"}, // چ
            { new int[] { 0x6A9 }, "k"}, // ک
            { new int[] { 0x6AF }, "g"}, // گ
            { new int[] { 0x67E }, "p"}, // پ
            { new int[] { 0x698 }, "zh"}, // ژ
            { new int[] { 0x6CC }, "y"}, // ی
            { new int[] { 0x6F0 }, "0"}, // ۰
            { new int[] { 0x6F1 }, "1"}, // ۱
            { new int[] { 0x6F2 }, "2"}, // ۲
            { new int[] { 0x6F3 }, "3"}, // ۳
            { new int[] { 0x6F4 }, "4"}, // ۴
            { new int[] { 0x6F5 }, "5"}, // ۵
            { new int[] { 0x6F6 }, "6"}, // ۶
            { new int[] { 0x6F7 }, "7"}, // ۷
            { new int[] { 0x6F8 }, "8"}, // ۸
            { new int[] { 0x6F9 }, "9"}, // ۹

            // Pashto
            { new int[] { 0x67C }, "p"}, // ټ
            { new int[] { 0x681 }, "z"}, // ځ
            { new int[] { 0x685 }, "c"}, // څ
            { new int[] { 0x689 }, "d"}, // ډ
            { new int[] { 0xFEAB }, "d"}, // ﺫ
            { new int[] { 0xFEAD }, "r"}, // ﺭ
            { new int[] { 0x693 }, "r"}, // ړ
            { new int[] { 0xFEAF }, "z"}, // ﺯ
            { new int[] { 0x696 }, "g"}, // ږ
            { new int[] { 0x69A }, "x"}, // ښ
            { new int[] { 0x6AB }, "g"}, // ګ
            { new int[] { 0x6BC }, "n"}, // ڼ
            { new int[] { 0x6C0 }, "e"}, // ۀ
            { new int[] { 0x6D0 }, "e"}, // ې
            { new int[] { 0x6CD }, "ai"}, // ۍ

            // Urdu
            { new int[] { 0x679 }, "t"}, // ٹ
            { new int[] { 0x688 }, "d"}, // ڈ
            { new int[] { 0x691 }, "r"}, // ڑ
            { new int[] { 0x6BA }, "n"}, // ں
            { new int[] { 0x6C1 }, "h"}, // ہ
            { new int[] { 0x6BE }, "h"}, // ھ
            { new int[] { 0x6D2 }, "e"}, // ے

            // Russian
            { new int[] { 0x410 }, "A"}, // А
            { new int[] { 0x430 }, "a"}, // а
            { new int[] { 0x411 }, "B"}, // Б
            { new int[] { 0x431 }, "b"}, // б
            { new int[] { 0x412 }, "V"}, // В
            { new int[] { 0x432 }, "v"}, // в
            { new int[] { 0x413 }, "G"}, // Г
            { new int[] { 0x433 }, "g"}, // г
            { new int[] { 0x414 }, "D"}, // Д
            { new int[] { 0x434 }, "d"}, // д
            { new int[] { 0x44A, 0x435 }, "ye"}, // ъе
            { new int[] { 0x42A, 0x435 }, "Ye"}, // Ъе
            { new int[] { 0x44A, 0x415 }, "yE"}, // ъЕ
            { new int[] { 0x42A, 0x415 }, "YE"}, // ЪЕ
            { new int[] { 0x415 }, "E"}, // Е
            { new int[] { 0x435 }, "e"}, // е
            { new int[] { 0x401 }, "Yo"}, // Ё
            { new int[] { 0x451 }, "yo"}, // ё
            { new int[] { 0x416 }, "Zh"}, // Ж
            { new int[] { 0x436 }, "zh"}, // ж
            { new int[] { 0x417 }, "Z"}, // З
            { new int[] { 0x437 }, "z"}, // з
            { new int[] { 0x418 }, "I"}, // И
            { new int[] { 0x438 }, "i"}, // и
            { new int[] { 0x44B, 0x439 }, "iy"}, // ый
            { new int[] { 0x42B, 0x439 }, "Iy"}, // Ый
            { new int[] { 0x42B, 0x419 }, "IY"}, // ЫЙ
            { new int[] { 0x44B, 0x419 }, "iY"}, // ыЙ
            { new int[] { 0x419 }, "Y"}, // Й
            { new int[] { 0x439 }, "y"}, // й
            { new int[] { 0x41A }, "K"}, // К
            { new int[] { 0x43A }, "k"}, // к
            { new int[] { 0x41B }, "L"}, // Л
            { new int[] { 0x43B }, "l"}, // л
            { new int[] { 0x41C }, "M"}, // М
            { new int[] { 0x43C }, "m"}, // м
            { new int[] { 0x41D }, "N"}, // Н
            { new int[] { 0x43D }, "n"}, // н
            { new int[] { 0x41E }, "O"}, // О
            { new int[] { 0x43E }, "o"}, // о
            { new int[] { 0x41F }, "P"}, // П
            { new int[] { 0x43F }, "p"}, // п
            { new int[] { 0x420 }, "R"}, // Р
            { new int[] { 0x440 }, "r"}, // р
            { new int[] { 0x421 }, "S"}, // С
            { new int[] { 0x441 }, "s"}, // с
            { new int[] { 0x422 }, "T"}, // Т
            { new int[] { 0x442 }, "t"}, // т
            { new int[] { 0x423 }, "U"}, // У
            { new int[] { 0x443 }, "u"}, // у
            { new int[] { 0x424 }, "F"}, // Ф
            { new int[] { 0x444 }, "f"}, // ф
            { new int[] { 0x425 }, "Kh"}, // Х
            { new int[] { 0x445 }, "kh"}, // х
            { new int[] { 0x426 }, "Ts"}, // Ц
            { new int[] { 0x446 }, "ts"}, // ц
            { new int[] { 0x427 }, "Ch"}, // Ч
            { new int[] { 0x447 }, "ch"}, // ч
            { new int[] { 0x428 }, "Sh"}, // Ш
            { new int[] { 0x448 }, "sh"}, // ш
            { new int[] { 0x429 }, "Sch"}, // Щ
            { new int[] { 0x449 }, "sch"}, // щ
            { new int[] { 0x42A }, ""}, // Ъ
            { new int[] { 0x44A }, ""}, // ъ
            { new int[] { 0x42B }, "Y"}, // Ы
            { new int[] { 0x44B }, "y"}, // ы
            { new int[] { 0x42C }, ""}, // Ь
            { new int[] { 0x44C }, ""}, // ь
            { new int[] { 0x42D }, "E"}, // Э
            { new int[] { 0x44D }, "e"}, // э
            { new int[] { 0x42E }, "Yu"}, // Ю
            { new int[] { 0x44E }, "yu"}, // ю
            { new int[] { 0x42F }, "Ya"}, // Я
            { new int[] { 0x44F }, "ya"}, // я

            // Romanian
            { new int[] { 0x103 }, "a"}, // ă
            { new int[] { 0x102 }, "A"}, // Ă
            { new int[] { 0x219 }, "s"}, // ș
            { new int[] { 0x218 }, "S"}, // Ș
            { new int[] { 0x21B }, "t"}, // ț
            { new int[] { 0x21A }, "T"}, // Ț
            { new int[] { 0x163 }, "t"}, // ţ
            { new int[] { 0x162 }, "T"}, // Ţ

            // Turkish
            { new int[] { 0x15F }, "s"}, // ş
            { new int[] { 0x15E }, "S"}, // Ş
            { new int[] { 0x11F }, "g"}, // ğ
            { new int[] { 0x11E }, "G"}, // Ğ
            { new int[] { 0x131 }, "i"}, // ı
            { new int[] { 0x130 }, "I"}, // İ

            // Armenian
            { new int[] { 0x561 }, "a"}, // ա
            { new int[] { 0x531 }, "A"}, // Ա
            { new int[] { 0x562 }, "b"}, // բ
            { new int[] { 0x532 }, "B"}, // Բ
            { new int[] { 0x563 }, "g"}, // գ
            { new int[] { 0x533 }, "G"}, // Գ
            { new int[] { 0x564 }, "d"}, // դ
            { new int[] { 0x534 }, "D"}, // Դ
            { new int[] { 0x565 }, "ye"}, // ե
            { new int[] { 0x535 }, "Ye"}, // Ե
            { new int[] { 0x566 }, "z"}, // զ
            { new int[] { 0x536 }, "Z"}, // Զ
            { new int[] { 0x567 }, "e"}, // է
            { new int[] { 0x537 }, "E"}, // Է
            { new int[] { 0x568 }, "y"}, // ը
            { new int[] { 0x538 }, "Y"}, // Ը
            { new int[] { 0x569 }, "t"}, // թ
            { new int[] { 0x539 }, "T"}, // Թ
            { new int[] { 0x56A }, "zh"}, // ժ
            { new int[] { 0x53A }, "Zh"}, // Ժ
            { new int[] { 0x56B }, "i"}, // ի
            { new int[] { 0x53B }, "I"}, // Ի
            { new int[] { 0x56C }, "l"}, // լ
            { new int[] { 0x53C }, "L"}, // Լ
            { new int[] { 0x56D }, "kh"}, // խ
            { new int[] { 0x53D }, "Kh"}, // Խ
            { new int[] { 0x56E }, "ts"}, // ծ
            { new int[] { 0x53E }, "Ts"}, // Ծ
            { new int[] { 0x56F }, "k"}, // կ
            { new int[] { 0x53F }, "K"}, // Կ
            { new int[] { 0x570 }, "h"}, // հ
            { new int[] { 0x540 }, "H"}, // Հ
            { new int[] { 0x571 }, "dz"}, // ձ
            { new int[] { 0x541 }, "Dz"}, // Ձ
            { new int[] { 0x572 }, "gh"}, // ղ
            { new int[] { 0x542 }, "Gh"}, // Ղ
            { new int[] { 0x573 }, "tch"}, // ճ
            { new int[] { 0x543 }, "Tch"}, // Ճ
            { new int[] { 0x574 }, "m"}, // մ
            { new int[] { 0x544 }, "M"}, // Մ
            { new int[] { 0x575 }, "y"}, // յ
            { new int[] { 0x545 }, "Y"}, // Յ
            { new int[] { 0x576 }, "n"}, // ն
            { new int[] { 0x546 }, "N"}, // Ն
            { new int[] { 0x577 }, "sh"}, // շ
            { new int[] { 0x547 }, "Sh"}, // Շ
            { new int[] { 0x578 }, "vo"}, // ո
            { new int[] { 0x548 }, "Vo"}, // Ո
            { new int[] { 0x579 }, "ch"}, // չ
            { new int[] { 0x549 }, "Ch"}, // Չ
            { new int[] { 0x57A }, "p"}, // պ
            { new int[] { 0x54A }, "P"}, // Պ
            { new int[] { 0x57B }, "j"}, // ջ
            { new int[] { 0x54B }, "J"}, // Ջ
            { new int[] { 0x57C }, "r"}, // ռ
            { new int[] { 0x54C }, "R"}, // Ռ
            { new int[] { 0x57D }, "s"}, // ս
            { new int[] { 0x54D }, "S"}, // Ս
            { new int[] { 0x57E }, "v"}, // վ
            { new int[] { 0x54E }, "V"}, // Վ
            { new int[] { 0x57F }, "t"}, // տ
            { new int[] { 0x54F }, "T"}, // Տ
            { new int[] { 0x580 }, "r"}, // ր
            { new int[] { 0x550 }, "R"}, // Ր
            { new int[] { 0x581 }, "c"}, // ց
            { new int[] { 0x551 }, "C"}, // Ց
            { new int[] { 0x578, 0x582 }, "u"}, // ու
            { new int[] { 0x548, 0x552 }, "U"}, // ՈՒ
            { new int[] { 0x548, 0x582 }, "U"}, // Ու
            { new int[] { 0x583 }, "p"}, // փ
            { new int[] { 0x553 }, "P"}, // Փ
            { new int[] { 0x584 }, "q"}, // ք
            { new int[] { 0x554 }, "Q"}, // Ք
            { new int[] { 0x585 }, "o"}, // օ
            { new int[] { 0x555 }, "O"}, // Օ
            { new int[] { 0x586 }, "f"}, // ֆ
            { new int[] { 0x556 }, "F"}, // Ֆ
            { new int[] { 0x587 }, "yev"}, // և

            // Georgian
            { new int[] { 0x10D0 }, "a"}, // ა
            { new int[] { 0x10D1 }, "b"}, // ბ
            { new int[] { 0x10D2 }, "g"}, // გ
            { new int[] { 0x10D3 }, "d"}, // დ
            { new int[] { 0x10D4 }, "e"}, // ე
            { new int[] { 0x10D5 }, "v"}, // ვ
            { new int[] { 0x10D6 }, "z"}, // ზ
            { new int[] { 0x10D7 }, "t"}, // თ
            { new int[] { 0x10D8 }, "i"}, // ი
            { new int[] { 0x10D9 }, "k"}, // კ
            { new int[] { 0x10DA }, "l"}, // ლ
            { new int[] { 0x10DB }, "m"}, // მ
            { new int[] { 0x10DC }, "n"}, // ნ
            { new int[] { 0x10DD }, "o"}, // ო
            { new int[] { 0x10DE }, "p"}, // პ
            { new int[] { 0x10DF }, "zh"}, // ჟ
            { new int[] { 0x10E0 }, "r"}, // რ
            { new int[] { 0x10E1 }, "s"}, // ს
            { new int[] { 0x10E2 }, "t"}, // ტ
            { new int[] { 0x10E3 }, "u"}, // უ
            { new int[] { 0x10E4 }, "ph"}, // ფ
            { new int[] { 0x10E5 }, "q"}, // ქ
            { new int[] { 0x10E6 }, "gh"}, // ღ
            { new int[] { 0x10E7 }, "k"}, // ყ
            { new int[] { 0x10E8 }, "sh"}, // შ
            { new int[] { 0x10E9 }, "ch"}, // ჩ
            { new int[] { 0x10EA }, "ts"}, // ც
            { new int[] { 0x10EB }, "dz"}, // ძ
            { new int[] { 0x10EC }, "ts"}, // წ
            { new int[] { 0x10ED }, "tch"}, // ჭ
            { new int[] { 0x10EE }, "kh"}, // ხ
            { new int[] { 0x10EF }, "j"}, // ჯ
            { new int[] { 0x10F0 }, "h"}, // ჰ

            // Czech
            { new int[] { 0x10D }, "c"}, // č
            { new int[] { 0x10F }, "d"}, // ď
            { new int[] { 0x11B }, "e"}, // ě
            { new int[] { 0x148 }, "n"}, // ň
            { new int[] { 0x159 }, "r"}, // ř
            { new int[] { 0x161 }, "s"}, // š
            { new int[] { 0x165 }, "t"}, // ť
            { new int[] { 0x16F }, "u"}, // ů
            { new int[] { 0x17E }, "z"}, // ž
            { new int[] { 0x10C }, "C"}, // Č
            { new int[] { 0x10E }, "D"}, // Ď
            { new int[] { 0x11A }, "E"}, // Ě
            { new int[] { 0x147 }, "N"}, // Ň
            { new int[] { 0x158 }, "R"}, // Ř
            { new int[] { 0x160 }, "S"}, // Š
            { new int[] { 0x164 }, "T"}, // Ť
            { new int[] { 0x16E }, "U"}, // Ů
            { new int[] { 0x17D }, "Z"}, // Ž

            // Dhivehi
            { new int[] { 0x780 }, "h"}, // ހ
            { new int[] { 0x781 }, "sh"}, // ށ
            { new int[] { 0x782 }, "n"}, // ނ
            { new int[] { 0x783 }, "r"}, // ރ
            { new int[] { 0x784 }, "b"}, // ބ
            { new int[] { 0x785 }, "lh"}, // ޅ
            { new int[] { 0x786 }, "k"}, // ކ
            { new int[] { 0x787 }, "a"}, // އ
            { new int[] { 0x788 }, "v"}, // ވ
            { new int[] { 0x789 }, "m"}, // މ
            { new int[] { 0x78A }, "f"}, // ފ
            { new int[] { 0x78B }, "dh"}, // ދ
            { new int[] { 0x78C }, "th"}, // ތ
            { new int[] { 0x78D }, "l"}, // ލ
            { new int[] { 0x78E }, "g"}, // ގ
            { new int[] { 0x78F }, "gn"}, // ޏ
            { new int[] { 0x790 }, "s"}, // ސ
            { new int[] { 0x791 }, "d"}, // ޑ
            { new int[] { 0x792 }, "z"}, // ޒ
            { new int[] { 0x793 }, "t"}, // ޓ
            { new int[] { 0x794 }, "y"}, // ޔ
            { new int[] { 0x795 }, "p"}, // ޕ
            { new int[] { 0x796 }, "j"}, // ޖ
            { new int[] { 0x797 }, "ch"}, // ޗ
            { new int[] { 0x798 }, "tt"}, // ޘ
            { new int[] { 0x799 }, "hh"}, // ޙ
            { new int[] { 0x79A }, "kh"}, // ޚ
            { new int[] { 0x79B }, "th"}, // ޛ
            { new int[] { 0x79C }, "z"}, // ޜ
            { new int[] { 0x79D }, "sh"}, // ޝ
            { new int[] { 0x79E }, "s"}, // ޞ
            { new int[] { 0x79F }, "d"}, // ޟ
            { new int[] { 0x7A0 }, "t"}, // ޠ
            { new int[] { 0x7A1 }, "z"}, // ޡ
            { new int[] { 0x7A2 }, "a"}, // ޢ
            { new int[] { 0x7A3 }, "gh"}, // ޣ
            { new int[] { 0x7A4 }, "q"}, // ޤ
            { new int[] { 0x7A5 }, "w"}, // ޥ
            { new int[] { 0x7A6 }, "a"}, // ަ
            { new int[] { 0x7A7 }, "aa"}, // ާ
            { new int[] { 0x7A8 }, "i"}, // ި
            { new int[] { 0x7A9 }, "ee"}, // ީ
            { new int[] { 0x7AA }, "u"}, // ު
            { new int[] { 0x7AB }, "oo"}, // ޫ
            { new int[] { 0x7AC }, "e"}, // ެ
            { new int[] { 0x7AD }, "ey"}, // ޭ
            { new int[] { 0x7AE }, "o"}, // ޮ
            { new int[] { 0x7AF }, "oa"}, // ޯ
            { new int[] { 0x7B0 }, ""}, // ް

            // Greek
            { new int[] { 0x3B1 }, "a"}, // α
            { new int[] { 0x3B2 }, "v"}, // β
            { new int[] { 0x3B3 }, "g"}, // γ
            { new int[] { 0x3B4 }, "d"}, // δ
            { new int[] { 0x3B5 }, "e"}, // ε
            { new int[] { 0x3B6 }, "z"}, // ζ
            { new int[] { 0x3B7 }, "i"}, // η
            { new int[] { 0x3B8 }, "th"}, // θ
            { new int[] { 0x3B9 }, "i"}, // ι
            { new int[] { 0x3BA }, "k"}, // κ
            { new int[] { 0x3BB }, "l"}, // λ
            { new int[] { 0x3BC }, "m"}, // μ
            { new int[] { 0x3BD }, "n"}, // ν
            { new int[] { 0x3BE }, "ks"}, // ξ
            { new int[] { 0x3BF }, "o"}, // ο
            { new int[] { 0x3C0 }, "p"}, // π
            { new int[] { 0x3C1 }, "r"}, // ρ
            { new int[] { 0x3C3 }, "s"}, // σ
            { new int[] { 0x3C4 }, "t"}, // τ
            { new int[] { 0x3C5 }, "y"}, // υ
            { new int[] { 0x3C6 }, "f"}, // φ
            { new int[] { 0x3C7 }, "x"}, // χ
            { new int[] { 0x3C8 }, "ps"}, // ψ
            { new int[] { 0x3C9 }, "o"}, // ω
            { new int[] { 0x3AC }, "a"}, // ά
            { new int[] { 0x3AD }, "e"}, // έ
            { new int[] { 0x3AF }, "i"}, // ί
            { new int[] { 0x3CC }, "o"}, // ό
            { new int[] { 0x3CD }, "y"}, // ύ
            { new int[] { 0x3AE }, "i"}, // ή
            { new int[] { 0x3CE }, "o"}, // ώ
            { new int[] { 0x3C2 }, "s"}, // ς
            { new int[] { 0x3CA }, "i"}, // ϊ
            { new int[] { 0x3B0 }, "y"}, // ΰ
            { new int[] { 0x3CB }, "y"}, // ϋ
            { new int[] { 0x390 }, "i"}, // ΐ
            { new int[] { 0x391 }, "A"}, // Α
            { new int[] { 0x392 }, "B"}, // Β
            { new int[] { 0x393 }, "G"}, // Γ
            { new int[] { 0x394 }, "D"}, // Δ
            { new int[] { 0x395 }, "E"}, // Ε
            { new int[] { 0x396 }, "Z"}, // Ζ
            { new int[] { 0x397 }, "I"}, // Η
            { new int[] { 0x398 }, "TH"}, // Θ
            { new int[] { 0x399 }, "I"}, // Ι
            { new int[] { 0x39A }, "K"}, // Κ
            { new int[] { 0x39B }, "L"}, // Λ
            { new int[] { 0x39C }, "M"}, // Μ
            { new int[] { 0x39D }, "N"}, // Ν
            { new int[] { 0x39E }, "KS"}, // Ξ
            { new int[] { 0x39F }, "O"}, // Ο
            { new int[] { 0x3A0 }, "P"}, // Π
            { new int[] { 0x3A1 }, "R"}, // Ρ
            { new int[] { 0x3A3 }, "S"}, // Σ
            { new int[] { 0x3A4 }, "T"}, // Τ
            { new int[] { 0x3A5 }, "Y"}, // Υ
            { new int[] { 0x3A6 }, "F"}, // Φ
            { new int[] { 0x3A7 }, "X"}, // Χ
            { new int[] { 0x3A8 }, "PS"}, // Ψ
            { new int[] { 0x3A9 }, "O"}, // Ω
            { new int[] { 0x386 }, "A"}, // Ά
            { new int[] { 0x388 }, "E"}, // Έ
            { new int[] { 0x38A }, "I"}, // Ί
            { new int[] { 0x38C }, "O"}, // Ό
            { new int[] { 0x38E }, "Y"}, // Ύ
            { new int[] { 0x389 }, "I"}, // Ή
            { new int[] { 0x38F }, "O"}, // Ώ
            { new int[] { 0x3AA }, "I"}, // Ϊ
            { new int[] { 0x3AB }, "Y"}, // Ϋ

            // Latvian
            { new int[] { 0x101 }, "a"}, // ā
            { new int[] { 0x113 }, "e"}, // ē
            { new int[] { 0x123 }, "g"}, // ģ
            { new int[] { 0x12B }, "i"}, // ī
            { new int[] { 0x137 }, "k"}, // ķ
            { new int[] { 0x13C }, "l"}, // ļ
            { new int[] { 0x146 }, "n"}, // ņ
            { new int[] { 0x16B }, "u"}, // ū
            { new int[] { 0x100 }, "A"}, // Ā
            { new int[] { 0x112 }, "E"}, // Ē
            { new int[] { 0x122 }, "G"}, // Ģ
            { new int[] { 0x12A }, "I"}, // Ī
            { new int[] { 0x136 }, "K"}, // Ķ
            { new int[] { 0x13B }, "L"}, // Ļ
            { new int[] { 0x145 }, "N"}, // Ņ
            { new int[] { 0x16A }, "U"}, // Ū

            // Lithuanian
            { new int[] { 0x105 }, "a"}, // ą
            { new int[] { 0x119 }, "e"}, // ę
            { new int[] { 0x117 }, "e"}, // ė
            { new int[] { 0x12F }, "i"}, // į
            { new int[] { 0x173 }, "u"}, // ų
            { new int[] { 0x104 }, "A"}, // Ą
            { new int[] { 0x118 }, "E"}, // Ę
            { new int[] { 0x116 }, "E"}, // Ė
            { new int[] { 0x12E }, "I"}, // Į
            { new int[] { 0x172 }, "U"}, // Ų

            // Macedonian
            { new int[] { 0x40C }, "Kj"}, // Ќ
            { new int[] { 0x45C }, "kj"}, // ќ
            { new int[] { 0x409 }, "Lj"}, // Љ
            { new int[] { 0x459 }, "lj"}, // љ
            { new int[] { 0x40A }, "Nj"}, // Њ
            { new int[] { 0x45A }, "nj"}, // њ
            { new int[] { 0x422, 0x441 }, "Ts"}, // Тс
            { new int[] { 0x442, 0x441 }, "ts"}, // тс

            // Polish
            { new int[] { 0x107 }, "c"}, // ć
            { new int[] { 0x142 }, "l"}, // ł
            { new int[] { 0x144 }, "n"}, // ń
            { new int[] { 0x15B }, "s"}, // ś
            { new int[] { 0x17A }, "z"}, // ź
            { new int[] { 0x17C }, "z"}, // ż
            { new int[] { 0x106 }, "C"}, // Ć
            { new int[] { 0x141 }, "L"}, // Ł
            { new int[] { 0x143 }, "N"}, // Ń
            { new int[] { 0x15A }, "S"}, // Ś
            { new int[] { 0x179 }, "Z"}, // Ź
            { new int[] { 0x17B }, "Z"}, // Ż

            // Ukrainian
            { new int[] { 0x404 }, "Ye"}, // Є
            { new int[] { 0x406 }, "I"}, // І
            { new int[] { 0x407 }, "Yi"}, // Ї
            { new int[] { 0x490 }, "G"}, // Ґ
            { new int[] { 0x454 }, "ye"}, // є
            { new int[] { 0x456 }, "i"}, // і
            { new int[] { 0x457 }, "yi"}, // ї
            { new int[] { 0x491 }, "g"}, // ґ

            // Dutch
            { new int[] { 0x132 }, "IJ"}, // Ĳ
            { new int[] { 0x133 }, "ij"}, // ĳ

            // Currencies
            { new int[] { 0xA2 }, "c"}, // ¢
            { new int[] { 0xA5 }, "Y"}, // ¥
            { new int[] { 0x7FF }, "b"}, // ߿
            { new int[] { 0x9F3 }, "t"}, // ৳
            { new int[] { 0xAF1 }, "Bo"}, // ૱
            { new int[] { 0xE3F }, "B"}, // ฿
            { new int[] { 0x20A0 }, "CE"}, // ₠
            { new int[] { 0x20A1 }, "C"}, // ₡
            { new int[] { 0x20A2 }, "Cr"}, // ₢
            { new int[] { 0x20A3 }, "F"}, // ₣
            { new int[] { 0x20A5 }, "m"}, // ₥
            { new int[] { 0x20A6 }, "N"}, // ₦
            { new int[] { 0x20A7 }, "Pt"}, // ₧
            { new int[] { 0x20A8 }, "Rs"}, // ₨
            { new int[] { 0x20A9 }, "W"}, // ₩
            { new int[] { 0x20AB }, "s"}, // ₫
            { new int[] { 0x20AC }, "E"}, // €
            { new int[] { 0x20AD }, "K"}, // ₭
            { new int[] { 0x20AE }, "T"}, // ₮
            { new int[] { 0x20AF }, "Dp"}, // ₯
            { new int[] { 0x20B0 }, "S"}, // ₰
            { new int[] { 0x20B1 }, "P"}, // ₱
            { new int[] { 0x20B2 }, "G"}, // ₲
            { new int[] { 0x20B3 }, "A"}, // ₳
            { new int[] { 0x20B4 }, "S"}, // ₴
            { new int[] { 0x20B5 }, "C"}, // ₵
            { new int[] { 0x20B6 }, "tt"}, // ₶
            { new int[] { 0x20B7 }, "S"}, // ₷
            { new int[] { 0x20B8 }, "T"}, // ₸
            { new int[] { 0x20B9 }, "R"}, // ₹
            { new int[] { 0x20BA }, "L"}, // ₺
            { new int[] { 0x20BD }, "P"}, // ₽
            { new int[] { 0x20BF }, "B"}, // ₿
            { new int[] { 0xFE69 }, "$"}, // ﹩
            { new int[] { 0xFFE0 }, "c"}, // ￠
            { new int[] { 0xFFE5 }, "Y"}, // ￥
            { new int[] { 0xFFE6 }, "W"}, // ￦

            // Latin
            { new int[] { 0x1D400 }, "A"}, // 𝐀
            { new int[] { 0x1D401 }, "B"}, // 𝐁
            { new int[] { 0x1D402 }, "C"}, // 𝐂
            { new int[] { 0x1D403 }, "D"}, // 𝐃
            { new int[] { 0x1D404 }, "E"}, // 𝐄
            { new int[] { 0x1D405 }, "F"}, // 𝐅
            { new int[] { 0x1D406 }, "G"}, // 𝐆
            { new int[] { 0x1D407 }, "H"}, // 𝐇
            { new int[] { 0x1D408 }, "I"}, // 𝐈
            { new int[] { 0x1D409 }, "J"}, // 𝐉
            { new int[] { 0x1D40A }, "K"}, // 𝐊
            { new int[] { 0x1D40B }, "L"}, // 𝐋
            { new int[] { 0x1D40C }, "M"}, // 𝐌
            { new int[] { 0x1D40D }, "N"}, // 𝐍
            { new int[] { 0x1D40E }, "O"}, // 𝐎
            { new int[] { 0x1D40F }, "P"}, // 𝐏
            { new int[] { 0x1D410 }, "Q"}, // 𝐐
            { new int[] { 0x1D411 }, "R"}, // 𝐑
            { new int[] { 0x1D412 }, "S"}, // 𝐒
            { new int[] { 0x1D413 }, "T"}, // 𝐓
            { new int[] { 0x1D414 }, "U"}, // 𝐔
            { new int[] { 0x1D415 }, "V"}, // 𝐕
            { new int[] { 0x1D416 }, "W"}, // 𝐖
            { new int[] { 0x1D417 }, "X"}, // 𝐗
            { new int[] { 0x1D418 }, "Y"}, // 𝐘
            { new int[] { 0x1D419 }, "Z"}, // 𝐙
            { new int[] { 0x1D41A }, "a"}, // 𝐚
            { new int[] { 0x1D41B }, "b"}, // 𝐛
            { new int[] { 0x1D41C }, "c"}, // 𝐜
            { new int[] { 0x1D41D }, "d"}, // 𝐝
            { new int[] { 0x1D41E }, "e"}, // 𝐞
            { new int[] { 0x1D41F }, "f"}, // 𝐟
            { new int[] { 0x1D420 }, "g"}, // 𝐠
            { new int[] { 0x1D421 }, "h"}, // 𝐡
            { new int[] { 0x1D422 }, "i"}, // 𝐢
            { new int[] { 0x1D423 }, "j"}, // 𝐣
            { new int[] { 0x1D424 }, "k"}, // 𝐤
            { new int[] { 0x1D425 }, "l"}, // 𝐥
            { new int[] { 0x1D426 }, "m"}, // 𝐦
            { new int[] { 0x1D427 }, "n"}, // 𝐧
            { new int[] { 0x1D428 }, "o"}, // 𝐨
            { new int[] { 0x1D429 }, "p"}, // 𝐩
            { new int[] { 0x1D42A }, "q"}, // 𝐪
            { new int[] { 0x1D42B }, "r"}, // 𝐫
            { new int[] { 0x1D42C }, "s"}, // 𝐬
            { new int[] { 0x1D42D }, "t"}, // 𝐭
            { new int[] { 0x1D42E }, "u"}, // 𝐮
            { new int[] { 0x1D42F }, "v"}, // 𝐯
            { new int[] { 0x1D430 }, "w"}, // 𝐰
            { new int[] { 0x1D431 }, "x"}, // 𝐱
            { new int[] { 0x1D432 }, "y"}, // 𝐲
            { new int[] { 0x1D433 }, "z"}, // 𝐳
            { new int[] { 0x1D434 }, "A"}, // 𝐴
            { new int[] { 0x1D435 }, "B"}, // 𝐵
            { new int[] { 0x1D436 }, "C"}, // 𝐶
            { new int[] { 0x1D437 }, "D"}, // 𝐷
            { new int[] { 0x1D438 }, "E"}, // 𝐸
            { new int[] { 0x1D439 }, "F"}, // 𝐹
            { new int[] { 0x1D43A }, "G"}, // 𝐺
            { new int[] { 0x1D43B }, "H"}, // 𝐻
            { new int[] { 0x1D43C }, "I"}, // 𝐼
            { new int[] { 0x1D43D }, "J"}, // 𝐽
            { new int[] { 0x1D43E }, "K"}, // 𝐾
            { new int[] { 0x1D43F }, "L"}, // 𝐿
            { new int[] { 0x1D440 }, "M"}, // 𝑀
            { new int[] { 0x1D441 }, "N"}, // 𝑁
            { new int[] { 0x1D442 }, "O"}, // 𝑂
            { new int[] { 0x1D443 }, "P"}, // 𝑃
            { new int[] { 0x1D444 }, "Q"}, // 𝑄
            { new int[] { 0x1D445 }, "R"}, // 𝑅
            { new int[] { 0x1D446 }, "S"}, // 𝑆
            { new int[] { 0x1D447 }, "T"}, // 𝑇
            { new int[] { 0x1D448 }, "U"}, // 𝑈
            { new int[] { 0x1D449 }, "V"}, // 𝑉
            { new int[] { 0x1D44A }, "W"}, // 𝑊
            { new int[] { 0x1D44B }, "X"}, // 𝑋
            { new int[] { 0x1D44C }, "Y"}, // 𝑌
            { new int[] { 0x1D44D }, "Z"}, // 𝑍
            { new int[] { 0x1D44E }, "a"}, // 𝑎
            { new int[] { 0x1D44F }, "b"}, // 𝑏
            { new int[] { 0x1D450 }, "c"}, // 𝑐
            { new int[] { 0x1D451 }, "d"}, // 𝑑
            { new int[] { 0x1D452 }, "e"}, // 𝑒
            { new int[] { 0x1D453 }, "f"}, // 𝑓
            { new int[] { 0x1D454 }, "g"}, // 𝑔
            { new int[] { 0x1D456 }, "i"}, // 𝑖
            { new int[] { 0x1D457 }, "j"}, // 𝑗
            { new int[] { 0x1D458 }, "k"}, // 𝑘
            { new int[] { 0x1D459 }, "l"}, // 𝑙
            { new int[] { 0x1D45A }, "m"}, // 𝑚
            { new int[] { 0x1D45B }, "n"}, // 𝑛
            { new int[] { 0x1D45C }, "o"}, // 𝑜
            { new int[] { 0x1D45D }, "p"}, // 𝑝
            { new int[] { 0x1D45E }, "q"}, // 𝑞
            { new int[] { 0x1D45F }, "r"}, // 𝑟
            { new int[] { 0x1D460 }, "s"}, // 𝑠
            { new int[] { 0x1D461 }, "t"}, // 𝑡
            { new int[] { 0x1D462 }, "u"}, // 𝑢
            { new int[] { 0x1D463 }, "v"}, // 𝑣
            { new int[] { 0x1D464 }, "w"}, // 𝑤
            { new int[] { 0x1D465 }, "x"}, // 𝑥
            { new int[] { 0x1D466 }, "y"}, // 𝑦
            { new int[] { 0x1D467 }, "z"}, // 𝑧
            { new int[] { 0x1D468 }, "A"}, // 𝑨
            { new int[] { 0x1D469 }, "B"}, // 𝑩
            { new int[] { 0x1D46A }, "C"}, // 𝑪
            { new int[] { 0x1D46B }, "D"}, // 𝑫
            { new int[] { 0x1D46C }, "E"}, // 𝑬
            { new int[] { 0x1D46D }, "F"}, // 𝑭
            { new int[] { 0x1D46E }, "G"}, // 𝑮
            { new int[] { 0x1D46F }, "H"}, // 𝑯
            { new int[] { 0x1D470 }, "I"}, // 𝑰
            { new int[] { 0x1D471 }, "J"}, // 𝑱
            { new int[] { 0x1D472 }, "K"}, // 𝑲
            { new int[] { 0x1D473 }, "L"}, // 𝑳
            { new int[] { 0x1D474 }, "M"}, // 𝑴
            { new int[] { 0x1D475 }, "N"}, // 𝑵
            { new int[] { 0x1D476 }, "O"}, // 𝑶
            { new int[] { 0x1D477 }, "P"}, // 𝑷
            { new int[] { 0x1D478 }, "Q"}, // 𝑸
            { new int[] { 0x1D479 }, "R"}, // 𝑹
            { new int[] { 0x1D47A }, "S"}, // 𝑺
            { new int[] { 0x1D47B }, "T"}, // 𝑻
            { new int[] { 0x1D47C }, "U"}, // 𝑼
            { new int[] { 0x1D47D }, "V"}, // 𝑽
            { new int[] { 0x1D47E }, "W"}, // 𝑾
            { new int[] { 0x1D47F }, "X"}, // 𝑿
            { new int[] { 0x1D480 }, "Y"}, // 𝒀
            { new int[] { 0x1D481 }, "Z"}, // 𝒁
            { new int[] { 0x1D482 }, "a"}, // 𝒂
            { new int[] { 0x1D483 }, "b"}, // 𝒃
            { new int[] { 0x1D484 }, "c"}, // 𝒄
            { new int[] { 0x1D485 }, "d"}, // 𝒅
            { new int[] { 0x1D486 }, "e"}, // 𝒆
            { new int[] { 0x1D487 }, "f"}, // 𝒇
            { new int[] { 0x1D488 }, "g"}, // 𝒈
            { new int[] { 0x1D489 }, "h"}, // 𝒉
            { new int[] { 0x1D48A }, "i"}, // 𝒊
            { new int[] { 0x1D48B }, "j"}, // 𝒋
            { new int[] { 0x1D48C }, "k"}, // 𝒌
            { new int[] { 0x1D48D }, "l"}, // 𝒍
            { new int[] { 0x1D48E }, "m"}, // 𝒎
            { new int[] { 0x1D48F }, "n"}, // 𝒏
            { new int[] { 0x1D490 }, "o"}, // 𝒐
            { new int[] { 0x1D491 }, "p"}, // 𝒑
            { new int[] { 0x1D492 }, "q"}, // 𝒒
            { new int[] { 0x1D493 }, "r"}, // 𝒓
            { new int[] { 0x1D494 }, "s"}, // 𝒔
            { new int[] { 0x1D495 }, "t"}, // 𝒕
            { new int[] { 0x1D496 }, "u"}, // 𝒖
            { new int[] { 0x1D497 }, "v"}, // 𝒗
            { new int[] { 0x1D498 }, "w"}, // 𝒘
            { new int[] { 0x1D499 }, "x"}, // 𝒙
            { new int[] { 0x1D49A }, "y"}, // 𝒚
            { new int[] { 0x1D49B }, "z"}, // 𝒛
            { new int[] { 0x1D49C }, "A"}, // 𝒜
            { new int[] { 0x1D49E }, "C"}, // 𝒞
            { new int[] { 0x1D49F }, "D"}, // 𝒟
            { new int[] { 0x1D4A2 }, "g"}, // 𝒢
            { new int[] { 0x1D4A5 }, "J"}, // 𝒥
            { new int[] { 0x1D4A6 }, "K"}, // 𝒦
            { new int[] { 0x1D4A9 }, "N"}, // 𝒩
            { new int[] { 0x1D4AA }, "O"}, // 𝒪
            { new int[] { 0x1D4AB }, "P"}, // 𝒫
            { new int[] { 0x1D4AC }, "Q"}, // 𝒬
            { new int[] { 0x1D4AE }, "S"}, // 𝒮
            { new int[] { 0x1D4AF }, "T"}, // 𝒯
            { new int[] { 0x1D4B0 }, "U"}, // 𝒰
            { new int[] { 0x1D4B1 }, "V"}, // 𝒱
            { new int[] { 0x1D4B2 }, "W"}, // 𝒲
            { new int[] { 0x1D4B3 }, "X"}, // 𝒳
            { new int[] { 0x1D4B4 }, "Y"}, // 𝒴
            { new int[] { 0x1D4B5 }, "Z"}, // 𝒵
            { new int[] { 0x1D4B6 }, "a"}, // 𝒶
            { new int[] { 0x1D4B7 }, "b"}, // 𝒷
            { new int[] { 0x1D4B8 }, "c"}, // 𝒸
            { new int[] { 0x1D4B9 }, "d"}, // 𝒹
            { new int[] { 0x1D4BB }, "f"}, // 𝒻
            { new int[] { 0x1D4BD }, "h"}, // 𝒽
            { new int[] { 0x1D4BE }, "i"}, // 𝒾
            { new int[] { 0x1D4BF }, "j"}, // 𝒿
            { new int[] { 0x1D4C0 }, "h"}, // 𝓀
            { new int[] { 0x1D4C1 }, "l"}, // 𝓁
            { new int[] { 0x1D4C2 }, "m"}, // 𝓂
            { new int[] { 0x1D4C3 }, "n"}, // 𝓃
            { new int[] { 0x1D4C5 }, "p"}, // 𝓅
            { new int[] { 0x1D4C6 }, "q"}, // 𝓆
            { new int[] { 0x1D4C7 }, "r"}, // 𝓇
            { new int[] { 0x1D4C8 }, "s"}, // 𝓈
            { new int[] { 0x1D4C9 }, "t"}, // 𝓉
            { new int[] { 0x1D4CA }, "u"}, // 𝓊
            { new int[] { 0x1D4CB }, "v"}, // 𝓋
            { new int[] { 0x1D4CC }, "w"}, // 𝓌
            { new int[] { 0x1D4CD }, "x"}, // 𝓍
            { new int[] { 0x1D4CE }, "y"}, // 𝓎
            { new int[] { 0x1D4CF }, "z"}, // 𝓏
            { new int[] { 0x1D4D0 }, "A"}, // 𝓐
            { new int[] { 0x1D4D1 }, "B"}, // 𝓑
            { new int[] { 0x1D4D2 }, "C"}, // 𝓒
            { new int[] { 0x1D4D3 }, "D"}, // 𝓓
            { new int[] { 0x1D4D4 }, "E"}, // 𝓔
            { new int[] { 0x1D4D5 }, "F"}, // 𝓕
            { new int[] { 0x1D4D6 }, "G"}, // 𝓖
            { new int[] { 0x1D4D7 }, "H"}, // 𝓗
            { new int[] { 0x1D4D8 }, "I"}, // 𝓘
            { new int[] { 0x1D4D9 }, "J"}, // 𝓙
            { new int[] { 0x1D4DA }, "K"}, // 𝓚
            { new int[] { 0x1D4DB }, "L"}, // 𝓛
            { new int[] { 0x1D4DC }, "M"}, // 𝓜
            { new int[] { 0x1D4DD }, "N"}, // 𝓝
            { new int[] { 0x1D4DE }, "O"}, // 𝓞
            { new int[] { 0x1D4DF }, "P"}, // 𝓟
            { new int[] { 0x1D4E0 }, "Q"}, // 𝓠
            { new int[] { 0x1D4E1 }, "R"}, // 𝓡
            { new int[] { 0x1D4E2 }, "S"}, // 𝓢
            { new int[] { 0x1D4E3 }, "T"}, // 𝓣
            { new int[] { 0x1D4E4 }, "U"}, // 𝓤
            { new int[] { 0x1D4E5 }, "V"}, // 𝓥
            { new int[] { 0x1D4E6 }, "W"}, // 𝓦
            { new int[] { 0x1D4E7 }, "X"}, // 𝓧
            { new int[] { 0x1D4E8 }, "Y"}, // 𝓨
            { new int[] { 0x1D4E9 }, "Z"}, // 𝓩
            { new int[] { 0x1D4EA }, "a"}, // 𝓪
            { new int[] { 0x1D4EB }, "b"}, // 𝓫
            { new int[] { 0x1D4EC }, "c"}, // 𝓬
            { new int[] { 0x1D4ED }, "d"}, // 𝓭
            { new int[] { 0x1D4EE }, "e"}, // 𝓮
            { new int[] { 0x1D4EF }, "f"}, // 𝓯
            { new int[] { 0x1D4F0 }, "g"}, // 𝓰
            { new int[] { 0x1D4F1 }, "h"}, // 𝓱
            { new int[] { 0x1D4F2 }, "i"}, // 𝓲
            { new int[] { 0x1D4F3 }, "j"}, // 𝓳
            { new int[] { 0x1D4F4 }, "k"}, // 𝓴
            { new int[] { 0x1D4F5 }, "l"}, // 𝓵
            { new int[] { 0x1D4F6 }, "m"}, // 𝓶
            { new int[] { 0x1D4F7 }, "n"}, // 𝓷
            { new int[] { 0x1D4F8 }, "o"}, // 𝓸
            { new int[] { 0x1D4F9 }, "p"}, // 𝓹
            { new int[] { 0x1D4FA }, "q"}, // 𝓺
            { new int[] { 0x1D4FB }, "r"}, // 𝓻
            { new int[] { 0x1D4FC }, "s"}, // 𝓼
            { new int[] { 0x1D4FD }, "t"}, // 𝓽
            { new int[] { 0x1D4FE }, "u"}, // 𝓾
            { new int[] { 0x1D4FF }, "v"}, // 𝓿
            { new int[] { 0x1D500 }, "w"}, // 𝔀
            { new int[] { 0x1D501 }, "x"}, // 𝔁
            { new int[] { 0x1D502 }, "y"}, // 𝔂
            { new int[] { 0x1D503 }, "z"}, // 𝔃
            { new int[] { 0x1D504 }, "A"}, // 𝔄
            { new int[] { 0x1D505 }, "B"}, // 𝔅
            { new int[] { 0x1D507 }, "D"}, // 𝔇
            { new int[] { 0x1D508 }, "E"}, // 𝔈
            { new int[] { 0x1D509 }, "F"}, // 𝔉
            { new int[] { 0x1D50A }, "G"}, // 𝔊
            { new int[] { 0x1D50D }, "J"}, // 𝔍
            { new int[] { 0x1D50E }, "K"}, // 𝔎
            { new int[] { 0x1D50F }, "L"}, // 𝔏
            { new int[] { 0x1D510 }, "M"}, // 𝔐
            { new int[] { 0x1D511 }, "N"}, // 𝔑
            { new int[] { 0x1D512 }, "O"}, // 𝔒
            { new int[] { 0x1D513 }, "P"}, // 𝔓
            { new int[] { 0x1D514 }, "Q"}, // 𝔔
            { new int[] { 0x1D516 }, "S"}, // 𝔖
            { new int[] { 0x1D517 }, "T"}, // 𝔗
            { new int[] { 0x1D518 }, "U"}, // 𝔘
            { new int[] { 0x1D519 }, "V"}, // 𝔙
            { new int[] { 0x1D51A }, "W"}, // 𝔚
            { new int[] { 0x1D51B }, "X"}, // 𝔛
            { new int[] { 0x1D51C }, "Y"}, // 𝔜
            { new int[] { 0x1D51E }, "a"}, // 𝔞
            { new int[] { 0x1D51F }, "b"}, // 𝔟
            { new int[] { 0x1D520 }, "c"}, // 𝔠
            { new int[] { 0x1D521 }, "d"}, // 𝔡
            { new int[] { 0x1D522 }, "e"}, // 𝔢
            { new int[] { 0x1D523 }, "f"}, // 𝔣
            { new int[] { 0x1D524 }, "g"}, // 𝔤
            { new int[] { 0x1D525 }, "h"}, // 𝔥
            { new int[] { 0x1D526 }, "i"}, // 𝔦
            { new int[] { 0x1D527 }, "j"}, // 𝔧
            { new int[] { 0x1D528 }, "k"}, // 𝔨
            { new int[] { 0x1D529 }, "l"}, // 𝔩
            { new int[] { 0x1D52A }, "m"}, // 𝔪
            { new int[] { 0x1D52B }, "n"}, // 𝔫
            { new int[] { 0x1D52C }, "o"}, // 𝔬
            { new int[] { 0x1D52D }, "p"}, // 𝔭
            { new int[] { 0x1D52E }, "q"}, // 𝔮
            { new int[] { 0x1D52F }, "r"}, // 𝔯
            { new int[] { 0x1D530 }, "s"}, // 𝔰
            { new int[] { 0x1D531 }, "t"}, // 𝔱
            { new int[] { 0x1D532 }, "u"}, // 𝔲
            { new int[] { 0x1D533 }, "v"}, // 𝔳
            { new int[] { 0x1D534 }, "w"}, // 𝔴
            { new int[] { 0x1D535 }, "x"}, // 𝔵
            { new int[] { 0x1D536 }, "y"}, // 𝔶
            { new int[] { 0x1D537 }, "z"}, // 𝔷
            { new int[] { 0x1D538 }, "A"}, // 𝔸
            { new int[] { 0x1D539 }, "B"}, // 𝔹
            { new int[] { 0x1D53B }, "D"}, // 𝔻
            { new int[] { 0x1D53C }, "E"}, // 𝔼
            { new int[] { 0x1D53D }, "F"}, // 𝔽
            { new int[] { 0x1D53E }, "G"}, // 𝔾
            { new int[] { 0x1D540 }, "I"}, // 𝕀
            { new int[] { 0x1D541 }, "J"}, // 𝕁
            { new int[] { 0x1D542 }, "K"}, // 𝕂
            { new int[] { 0x1D543 }, "L"}, // 𝕃
            { new int[] { 0x1D544 }, "M"}, // 𝕄
            { new int[] { 0x1D546 }, "N"}, // 𝕆
            { new int[] { 0x1D54A }, "S"}, // 𝕊
            { new int[] { 0x1D54B }, "T"}, // 𝕋
            { new int[] { 0x1D54C }, "U"}, // 𝕌
            { new int[] { 0x1D54D }, "V"}, // 𝕍
            { new int[] { 0x1D54E }, "W"}, // 𝕎
            { new int[] { 0x1D54F }, "X"}, // 𝕏
            { new int[] { 0x1D550 }, "Y"}, // 𝕐
            { new int[] { 0x1D552 }, "a"}, // 𝕒
            { new int[] { 0x1D553 }, "b"}, // 𝕓
            { new int[] { 0x1D554 }, "c"}, // 𝕔
            { new int[] { 0x1D555 }, "d"}, // 𝕕
            { new int[] { 0x1D556 }, "e"}, // 𝕖
            { new int[] { 0x1D557 }, "f"}, // 𝕗
            { new int[] { 0x1D558 }, "g"}, // 𝕘
            { new int[] { 0x1D559 }, "h"}, // 𝕙
            { new int[] { 0x1D55A }, "i"}, // 𝕚
            { new int[] { 0x1D55B }, "j"}, // 𝕛
            { new int[] { 0x1D55C }, "k"}, // 𝕜
            { new int[] { 0x1D55D }, "l"}, // 𝕝
            { new int[] { 0x1D55E }, "m"}, // 𝕞
            { new int[] { 0x1D55F }, "n"}, // 𝕟
            { new int[] { 0x1D560 }, "o"}, // 𝕠
            { new int[] { 0x1D561 }, "p"}, // 𝕡
            { new int[] { 0x1D562 }, "q"}, // 𝕢
            { new int[] { 0x1D563 }, "r"}, // 𝕣
            { new int[] { 0x1D564 }, "s"}, // 𝕤
            { new int[] { 0x1D565 }, "t"}, // 𝕥
            { new int[] { 0x1D566 }, "u"}, // 𝕦
            { new int[] { 0x1D567 }, "v"}, // 𝕧
            { new int[] { 0x1D568 }, "w"}, // 𝕨
            { new int[] { 0x1D569 }, "x"}, // 𝕩
            { new int[] { 0x1D56A }, "y"}, // 𝕪
            { new int[] { 0x1D56B }, "z"}, // 𝕫
            { new int[] { 0x1D56C }, "A"}, // 𝕬
            { new int[] { 0x1D56D }, "B"}, // 𝕭
            { new int[] { 0x1D56E }, "C"}, // 𝕮
            { new int[] { 0x1D56F }, "D"}, // 𝕯
            { new int[] { 0x1D570 }, "E"}, // 𝕰
            { new int[] { 0x1D571 }, "F"}, // 𝕱
            { new int[] { 0x1D572 }, "G"}, // 𝕲
            { new int[] { 0x1D573 }, "H"}, // 𝕳
            { new int[] { 0x1D574 }, "I"}, // 𝕴
            { new int[] { 0x1D575 }, "J"}, // 𝕵
            { new int[] { 0x1D576 }, "K"}, // 𝕶
            { new int[] { 0x1D577 }, "L"}, // 𝕷
            { new int[] { 0x1D578 }, "M"}, // 𝕸
            { new int[] { 0x1D579 }, "N"}, // 𝕹
            { new int[] { 0x1D57A }, "O"}, // 𝕺
            { new int[] { 0x1D57B }, "P"}, // 𝕻
            { new int[] { 0x1D57C }, "Q"}, // 𝕼
            { new int[] { 0x1D57D }, "R"}, // 𝕽
            { new int[] { 0x1D57E }, "S"}, // 𝕾
            { new int[] { 0x1D57F }, "T"}, // 𝕿
            { new int[] { 0x1D580 }, "U"}, // 𝖀
            { new int[] { 0x1D581 }, "V"}, // 𝖁
            { new int[] { 0x1D582 }, "W"}, // 𝖂
            { new int[] { 0x1D583 }, "X"}, // 𝖃
            { new int[] { 0x1D584 }, "Y"}, // 𝖄
            { new int[] { 0x1D585 }, "Z"}, // 𝖅
            { new int[] { 0x1D586 }, "a"}, // 𝖆
            { new int[] { 0x1D587 }, "b"}, // 𝖇
            { new int[] { 0x1D588 }, "c"}, // 𝖈
            { new int[] { 0x1D589 }, "d"}, // 𝖉
            { new int[] { 0x1D58A }, "e"}, // 𝖊
            { new int[] { 0x1D58B }, "f"}, // 𝖋
            { new int[] { 0x1D58C }, "g"}, // 𝖌
            { new int[] { 0x1D58D }, "h"}, // 𝖍
            { new int[] { 0x1D58E }, "i"}, // 𝖎
            { new int[] { 0x1D58F }, "j"}, // 𝖏
            { new int[] { 0x1D590 }, "k"}, // 𝖐
            { new int[] { 0x1D591 }, "l"}, // 𝖑
            { new int[] { 0x1D592 }, "m"}, // 𝖒
            { new int[] { 0x1D593 }, "n"}, // 𝖓
            { new int[] { 0x1D594 }, "o"}, // 𝖔
            { new int[] { 0x1D595 }, "p"}, // 𝖕
            { new int[] { 0x1D596 }, "q"}, // 𝖖
            { new int[] { 0x1D597 }, "r"}, // 𝖗
            { new int[] { 0x1D598 }, "s"}, // 𝖘
            { new int[] { 0x1D599 }, "t"}, // 𝖙
            { new int[] { 0x1D59A }, "u"}, // 𝖚
            { new int[] { 0x1D59B }, "v"}, // 𝖛
            { new int[] { 0x1D59C }, "w"}, // 𝖜
            { new int[] { 0x1D59D }, "x"}, // 𝖝
            { new int[] { 0x1D59E }, "y"}, // 𝖞
            { new int[] { 0x1D59F }, "z"}, // 𝖟
            { new int[] { 0x1D5A0 }, "A"}, // 𝖠
            { new int[] { 0x1D5A1 }, "B"}, // 𝖡
            { new int[] { 0x1D5A2 }, "C"}, // 𝖢
            { new int[] { 0x1D5A3 }, "D"}, // 𝖣
            { new int[] { 0x1D5A4 }, "E"}, // 𝖤
            { new int[] { 0x1D5A5 }, "F"}, // 𝖥
            { new int[] { 0x1D5A6 }, "G"}, // 𝖦
            { new int[] { 0x1D5A7 }, "H"}, // 𝖧
            { new int[] { 0x1D5A8 }, "I"}, // 𝖨
            { new int[] { 0x1D5A9 }, "J"}, // 𝖩
            { new int[] { 0x1D5AA }, "K"}, // 𝖪
            { new int[] { 0x1D5AB }, "L"}, // 𝖫
            { new int[] { 0x1D5AC }, "M"}, // 𝖬
            { new int[] { 0x1D5AD }, "N"}, // 𝖭
            { new int[] { 0x1D5AE }, "O"}, // 𝖮
            { new int[] { 0x1D5AF }, "P"}, // 𝖯
            { new int[] { 0x1D5B0 }, "Q"}, // 𝖰
            { new int[] { 0x1D5B1 }, "R"}, // 𝖱
            { new int[] { 0x1D5B2 }, "S"}, // 𝖲
            { new int[] { 0x1D5B3 }, "T"}, // 𝖳
            { new int[] { 0x1D5B4 }, "U"}, // 𝖴
            { new int[] { 0x1D5B5 }, "V"}, // 𝖵
            { new int[] { 0x1D5B6 }, "W"}, // 𝖶
            { new int[] { 0x1D5B7 }, "X"}, // 𝖷
            { new int[] { 0x1D5B8 }, "Y"}, // 𝖸
            { new int[] { 0x1D5B9 }, "Z"}, // 𝖹
            { new int[] { 0x1D5BA }, "a"}, // 𝖺
            { new int[] { 0x1D5BB }, "b"}, // 𝖻
            { new int[] { 0x1D5BC }, "c"}, // 𝖼
            { new int[] { 0x1D5BD }, "d"}, // 𝖽
            { new int[] { 0x1D5BE }, "e"}, // 𝖾
            { new int[] { 0x1D5BF }, "f"}, // 𝖿
            { new int[] { 0x1D5C0 }, "g"}, // 𝗀
            { new int[] { 0x1D5C1 }, "h"}, // 𝗁
            { new int[] { 0x1D5C2 }, "i"}, // 𝗂
            { new int[] { 0x1D5C3 }, "j"}, // 𝗃
            { new int[] { 0x1D5C4 }, "k"}, // 𝗄
            { new int[] { 0x1D5C5 }, "l"}, // 𝗅
            { new int[] { 0x1D5C6 }, "m"}, // 𝗆
            { new int[] { 0x1D5C7 }, "n"}, // 𝗇
            { new int[] { 0x1D5C8 }, "o"}, // 𝗈
            { new int[] { 0x1D5C9 }, "p"}, // 𝗉
            { new int[] { 0x1D5CA }, "q"}, // 𝗊
            { new int[] { 0x1D5CB }, "r"}, // 𝗋
            { new int[] { 0x1D5CC }, "s"}, // 𝗌
            { new int[] { 0x1D5CD }, "t"}, // 𝗍
            { new int[] { 0x1D5CE }, "u"}, // 𝗎
            { new int[] { 0x1D5CF }, "v"}, // 𝗏
            { new int[] { 0x1D5D0 }, "w"}, // 𝗐
            { new int[] { 0x1D5D1 }, "x"}, // 𝗑
            { new int[] { 0x1D5D2 }, "y"}, // 𝗒
            { new int[] { 0x1D5D3 }, "z"}, // 𝗓
            { new int[] { 0x1D5D4 }, "A"}, // 𝗔
            { new int[] { 0x1D5D5 }, "B"}, // 𝗕
            { new int[] { 0x1D5D6 }, "C"}, // 𝗖
            { new int[] { 0x1D5D7 }, "D"}, // 𝗗
            { new int[] { 0x1D5D8 }, "E"}, // 𝗘
            { new int[] { 0x1D5D9 }, "F"}, // 𝗙
            { new int[] { 0x1D5DA }, "G"}, // 𝗚
            { new int[] { 0x1D5DB }, "H"}, // 𝗛
            { new int[] { 0x1D5DC }, "I"}, // 𝗜
            { new int[] { 0x1D5DD }, "J"}, // 𝗝
            { new int[] { 0x1D5DE }, "K"}, // 𝗞
            { new int[] { 0x1D5DF }, "L"}, // 𝗟
            { new int[] { 0x1D5E0 }, "M"}, // 𝗠
            { new int[] { 0x1D5E1 }, "N"}, // 𝗡
            { new int[] { 0x1D5E2 }, "O"}, // 𝗢
            { new int[] { 0x1D5E3 }, "P"}, // 𝗣
            { new int[] { 0x1D5E4 }, "Q"}, // 𝗤
            { new int[] { 0x1D5E5 }, "R"}, // 𝗥
            { new int[] { 0x1D5E6 }, "S"}, // 𝗦
            { new int[] { 0x1D5E7 }, "T"}, // 𝗧
            { new int[] { 0x1D5E8 }, "U"}, // 𝗨
            { new int[] { 0x1D5E9 }, "V"}, // 𝗩
            { new int[] { 0x1D5EA }, "W"}, // 𝗪
            { new int[] { 0x1D5EB }, "X"}, // 𝗫
            { new int[] { 0x1D5EC }, "Y"}, // 𝗬
            { new int[] { 0x1D5ED }, "Z"}, // 𝗭
            { new int[] { 0x1D5EE }, "a"}, // 𝗮
            { new int[] { 0x1D5EF }, "b"}, // 𝗯
            { new int[] { 0x1D5F0 }, "c"}, // 𝗰
            { new int[] { 0x1D5F1 }, "d"}, // 𝗱
            { new int[] { 0x1D5F2 }, "e"}, // 𝗲
            { new int[] { 0x1D5F3 }, "f"}, // 𝗳
            { new int[] { 0x1D5F4 }, "g"}, // 𝗴
            { new int[] { 0x1D5F5 }, "h"}, // 𝗵
            { new int[] { 0x1D5F6 }, "i"}, // 𝗶
            { new int[] { 0x1D5F7 }, "j"}, // 𝗷
            { new int[] { 0x1D5F8 }, "k"}, // 𝗸
            { new int[] { 0x1D5F9 }, "l"}, // 𝗹
            { new int[] { 0x1D5FA }, "m"}, // 𝗺
            { new int[] { 0x1D5FB }, "n"}, // 𝗻
            { new int[] { 0x1D5FC }, "o"}, // 𝗼
            { new int[] { 0x1D5FD }, "p"}, // 𝗽
            { new int[] { 0x1D5FE }, "q"}, // 𝗾
            { new int[] { 0x1D5FF }, "r"}, // 𝗿
            { new int[] { 0x1D600 }, "s"}, // 𝘀
            { new int[] { 0x1D601 }, "t"}, // 𝘁
            { new int[] { 0x1D602 }, "u"}, // 𝘂
            { new int[] { 0x1D603 }, "v"}, // 𝘃
            { new int[] { 0x1D604 }, "w"}, // 𝘄
            { new int[] { 0x1D605 }, "x"}, // 𝘅
            { new int[] { 0x1D606 }, "y"}, // 𝘆
            { new int[] { 0x1D607 }, "z"}, // 𝘇
            { new int[] { 0x1D608 }, "A"}, // 𝘈
            { new int[] { 0x1D609 }, "B"}, // 𝘉
            { new int[] { 0x1D60A }, "C"}, // 𝘊
            { new int[] { 0x1D60B }, "D"}, // 𝘋
            { new int[] { 0x1D60C }, "E"}, // 𝘌
            { new int[] { 0x1D60D }, "F"}, // 𝘍
            { new int[] { 0x1D60E }, "G"}, // 𝘎
            { new int[] { 0x1D60F }, "H"}, // 𝘏
            { new int[] { 0x1D610 }, "I"}, // 𝘐
            { new int[] { 0x1D611 }, "J"}, // 𝘑
            { new int[] { 0x1D612 }, "K"}, // 𝘒
            { new int[] { 0x1D613 }, "L"}, // 𝘓
            { new int[] { 0x1D614 }, "M"}, // 𝘔
            { new int[] { 0x1D615 }, "N"}, // 𝘕
            { new int[] { 0x1D616 }, "O"}, // 𝘖
            { new int[] { 0x1D617 }, "P"}, // 𝘗
            { new int[] { 0x1D618 }, "Q"}, // 𝘘
            { new int[] { 0x1D619 }, "R"}, // 𝘙
            { new int[] { 0x1D61A }, "S"}, // 𝘚
            { new int[] { 0x1D61B }, "T"}, // 𝘛
            { new int[] { 0x1D61C }, "U"}, // 𝘜
            { new int[] { 0x1D61D }, "V"}, // 𝘝
            { new int[] { 0x1D61E }, "W"}, // 𝘞
            { new int[] { 0x1D61F }, "X"}, // 𝘟
            { new int[] { 0x1D620 }, "Y"}, // 𝘠
            { new int[] { 0x1D621 }, "Z"}, // 𝘡
            { new int[] { 0x1D622 }, "a"}, // 𝘢
            { new int[] { 0x1D623 }, "b"}, // 𝘣
            { new int[] { 0x1D624 }, "c"}, // 𝘤
            { new int[] { 0x1D625 }, "d"}, // 𝘥
            { new int[] { 0x1D626 }, "e"}, // 𝘦
            { new int[] { 0x1D627 }, "f"}, // 𝘧
            { new int[] { 0x1D628 }, "g"}, // 𝘨
            { new int[] { 0x1D629 }, "h"}, // 𝘩
            { new int[] { 0x1D62A }, "i"}, // 𝘪
            { new int[] { 0x1D62B }, "j"}, // 𝘫
            { new int[] { 0x1D62C }, "k"}, // 𝘬
            { new int[] { 0x1D62D }, "l"}, // 𝘭
            { new int[] { 0x1D62E }, "m"}, // 𝘮
            { new int[] { 0x1D62F }, "n"}, // 𝘯
            { new int[] { 0x1D630 }, "o"}, // 𝘰
            { new int[] { 0x1D631 }, "p"}, // 𝘱
            { new int[] { 0x1D632 }, "q"}, // 𝘲
            { new int[] { 0x1D633 }, "r"}, // 𝘳
            { new int[] { 0x1D634 }, "s"}, // 𝘴
            { new int[] { 0x1D635 }, "t"}, // 𝘵
            { new int[] { 0x1D636 }, "u"}, // 𝘶
            { new int[] { 0x1D637 }, "v"}, // 𝘷
            { new int[] { 0x1D638 }, "w"}, // 𝘸
            { new int[] { 0x1D639 }, "x"}, // 𝘹
            { new int[] { 0x1D63A }, "y"}, // 𝘺
            { new int[] { 0x1D63B }, "z"}, // 𝘻
            { new int[] { 0x1D63C }, "A"}, // 𝘼
            { new int[] { 0x1D63D }, "B"}, // 𝘽
            { new int[] { 0x1D63E }, "C"}, // 𝘾
            { new int[] { 0x1D63F }, "D"}, // 𝘿
            { new int[] { 0x1D640 }, "E"}, // 𝙀
            { new int[] { 0x1D641 }, "F"}, // 𝙁
            { new int[] { 0x1D642 }, "G"}, // 𝙂
            { new int[] { 0x1D643 }, "H"}, // 𝙃
            { new int[] { 0x1D644 }, "I"}, // 𝙄
            { new int[] { 0x1D645 }, "J"}, // 𝙅
            { new int[] { 0x1D646 }, "K"}, // 𝙆
            { new int[] { 0x1D647 }, "L"}, // 𝙇
            { new int[] { 0x1D648 }, "M"}, // 𝙈
            { new int[] { 0x1D649 }, "N"}, // 𝙉
            { new int[] { 0x1D64A }, "O"}, // 𝙊
            { new int[] { 0x1D64B }, "P"}, // 𝙋
            { new int[] { 0x1D64C }, "Q"}, // 𝙌
            { new int[] { 0x1D64D }, "R"}, // 𝙍
            { new int[] { 0x1D64E }, "S"}, // 𝙎
            { new int[] { 0x1D64F }, "T"}, // 𝙏
            { new int[] { 0x1D650 }, "U"}, // 𝙐
            { new int[] { 0x1D651 }, "V"}, // 𝙑
            { new int[] { 0x1D652 }, "W"}, // 𝙒
            { new int[] { 0x1D653 }, "X"}, // 𝙓
            { new int[] { 0x1D654 }, "Y"}, // 𝙔
            { new int[] { 0x1D655 }, "Z"}, // 𝙕
            { new int[] { 0x1D656 }, "a"}, // 𝙖
            { new int[] { 0x1D657 }, "b"}, // 𝙗
            { new int[] { 0x1D658 }, "c"}, // 𝙘
            { new int[] { 0x1D659 }, "d"}, // 𝙙
            { new int[] { 0x1D65A }, "e"}, // 𝙚
            { new int[] { 0x1D65B }, "f"}, // 𝙛
            { new int[] { 0x1D65C }, "g"}, // 𝙜
            { new int[] { 0x1D65D }, "h"}, // 𝙝
            { new int[] { 0x1D65E }, "i"}, // 𝙞
            { new int[] { 0x1D65F }, "j"}, // 𝙟
            { new int[] { 0x1D660 }, "k"}, // 𝙠
            { new int[] { 0x1D661 }, "l"}, // 𝙡
            { new int[] { 0x1D662 }, "m"}, // 𝙢
            { new int[] { 0x1D663 }, "n"}, // 𝙣
            { new int[] { 0x1D664 }, "o"}, // 𝙤
            { new int[] { 0x1D665 }, "p"}, // 𝙥
            { new int[] { 0x1D666 }, "q"}, // 𝙦
            { new int[] { 0x1D667 }, "r"}, // 𝙧
            { new int[] { 0x1D668 }, "s"}, // 𝙨
            { new int[] { 0x1D669 }, "t"}, // 𝙩
            { new int[] { 0x1D66A }, "u"}, // 𝙪
            { new int[] { 0x1D66B }, "v"}, // 𝙫
            { new int[] { 0x1D66C }, "w"}, // 𝙬
            { new int[] { 0x1D66D }, "x"}, // 𝙭
            { new int[] { 0x1D66E }, "y"}, // 𝙮
            { new int[] { 0x1D66F }, "z"}, // 𝙯
            { new int[] { 0x1D670 }, "A"}, // 𝙰
            { new int[] { 0x1D671 }, "B"}, // 𝙱
            { new int[] { 0x1D672 }, "C"}, // 𝙲
            { new int[] { 0x1D673 }, "D"}, // 𝙳
            { new int[] { 0x1D674 }, "E"}, // 𝙴
            { new int[] { 0x1D675 }, "F"}, // 𝙵
            { new int[] { 0x1D676 }, "G"}, // 𝙶
            { new int[] { 0x1D677 }, "H"}, // 𝙷
            { new int[] { 0x1D678 }, "I"}, // 𝙸
            { new int[] { 0x1D679 }, "J"}, // 𝙹
            { new int[] { 0x1D67A }, "K"}, // 𝙺
            { new int[] { 0x1D67B }, "L"}, // 𝙻
            { new int[] { 0x1D67C }, "M"}, // 𝙼
            { new int[] { 0x1D67D }, "N"}, // 𝙽
            { new int[] { 0x1D67E }, "O"}, // 𝙾
            { new int[] { 0x1D67F }, "P"}, // 𝙿
            { new int[] { 0x1D680 }, "Q"}, // 𝚀
            { new int[] { 0x1D681 }, "R"}, // 𝚁
            { new int[] { 0x1D682 }, "S"}, // 𝚂
            { new int[] { 0x1D683 }, "T"}, // 𝚃
            { new int[] { 0x1D684 }, "U"}, // 𝚄
            { new int[] { 0x1D685 }, "V"}, // 𝚅
            { new int[] { 0x1D686 }, "W"}, // 𝚆
            { new int[] { 0x1D687 }, "X"}, // 𝚇
            { new int[] { 0x1D688 }, "Y"}, // 𝚈
            { new int[] { 0x1D689 }, "Z"}, // 𝚉
            { new int[] { 0x1D68A }, "a"}, // 𝚊
            { new int[] { 0x1D68B }, "b"}, // 𝚋
            { new int[] { 0x1D68C }, "c"}, // 𝚌
            { new int[] { 0x1D68D }, "d"}, // 𝚍
            { new int[] { 0x1D68E }, "e"}, // 𝚎
            { new int[] { 0x1D68F }, "f"}, // 𝚏
            { new int[] { 0x1D690 }, "g"}, // 𝚐
            { new int[] { 0x1D691 }, "h"}, // 𝚑
            { new int[] { 0x1D692 }, "i"}, // 𝚒
            { new int[] { 0x1D693 }, "j"}, // 𝚓
            { new int[] { 0x1D694 }, "k"}, // 𝚔
            { new int[] { 0x1D695 }, "l"}, // 𝚕
            { new int[] { 0x1D696 }, "m"}, // 𝚖
            { new int[] { 0x1D697 }, "n"}, // 𝚗
            { new int[] { 0x1D698 }, "o"}, // 𝚘
            { new int[] { 0x1D699 }, "p"}, // 𝚙
            { new int[] { 0x1D69A }, "q"}, // 𝚚
            { new int[] { 0x1D69B }, "r"}, // 𝚛
            { new int[] { 0x1D69C }, "s"}, // 𝚜
            { new int[] { 0x1D69D }, "t"}, // 𝚝
            { new int[] { 0x1D69E }, "u"}, // 𝚞
            { new int[] { 0x1D69F }, "v"}, // 𝚟
            { new int[] { 0x1D6A0 }, "w"}, // 𝚠
            { new int[] { 0x1D6A1 }, "x"}, // 𝚡
            { new int[] { 0x1D6A2 }, "y"}, // 𝚢
            { new int[] { 0x1D6A3 }, "z"}, // 𝚣

            // Dotless letters
            { new int[] { 0x1D6A4 }, "l"}, // 𝚤
            { new int[] { 0x1D6A5 }, "j"}, // 𝚥

            // Greek
            { new int[] { 0x1D6E2 }, "A"}, // 𝛢
            { new int[] { 0x1D6E3 }, "B"}, // 𝛣
            { new int[] { 0x1D6E4 }, "G"}, // 𝛤
            { new int[] { 0x1D6E5 }, "D"}, // 𝛥
            { new int[] { 0x1D6E6 }, "E"}, // 𝛦
            { new int[] { 0x1D6E7 }, "Z"}, // 𝛧
            { new int[] { 0x1D6E8 }, "I"}, // 𝛨
            { new int[] { 0x1D6E9 }, "TH"}, // 𝛩
            { new int[] { 0x1D6EA }, "I"}, // 𝛪
            { new int[] { 0x1D6EB }, "K"}, // 𝛫
            { new int[] { 0x1D6EC }, "L"}, // 𝛬
            { new int[] { 0x1D6ED }, "M"}, // 𝛭
            { new int[] { 0x1D6EE }, "N"}, // 𝛮
            { new int[] { 0x1D6EF }, "KS"}, // 𝛯
            { new int[] { 0x1D6F0 }, "O"}, // 𝛰
            { new int[] { 0x1D6F1 }, "P"}, // 𝛱
            { new int[] { 0x1D6F2 }, "R"}, // 𝛲
            { new int[] { 0x1D6F3 }, "TH"}, // 𝛳
            { new int[] { 0x1D6F4 }, "S"}, // 𝛴
            { new int[] { 0x1D6F5 }, "T"}, // 𝛵
            { new int[] { 0x1D6F6 }, "Y"}, // 𝛶
            { new int[] { 0x1D6F7 }, "F"}, // 𝛷
            { new int[] { 0x1D6F8 }, "x"}, // 𝛸
            { new int[] { 0x1D6F9 }, "PS"}, // 𝛹
            { new int[] { 0x1D6FA }, "O"}, // 𝛺
            { new int[] { 0x1D6FB }, "D"}, // 𝛻
            { new int[] { 0x1D6FC }, "a"}, // 𝛼
            { new int[] { 0x1D6FD }, "b"}, // 𝛽
            { new int[] { 0x1D6FE }, "g"}, // 𝛾
            { new int[] { 0x1D6FF }, "d"}, // 𝛿
            { new int[] { 0x1D700 }, "e"}, // 𝜀
            { new int[] { 0x1D701 }, "z"}, // 𝜁
            { new int[] { 0x1D702 }, "i"}, // 𝜂
            { new int[] { 0x1D703 }, "th"}, // 𝜃
            { new int[] { 0x1D704 }, "i"}, // 𝜄
            { new int[] { 0x1D705 }, "k"}, // 𝜅
            { new int[] { 0x1D706 }, "l"}, // 𝜆
            { new int[] { 0x1D707 }, "m"}, // 𝜇
            { new int[] { 0x1D708 }, "n"}, // 𝜈
            { new int[] { 0x1D709 }, "ks"}, // 𝜉
            { new int[] { 0x1D70A }, "o"}, // 𝜊
            { new int[] { 0x1D70B }, "p"}, // 𝜋
            { new int[] { 0x1D70C }, "r"}, // 𝜌
            { new int[] { 0x1D70D }, "s"}, // 𝜍
            { new int[] { 0x1D70E }, "s"}, // 𝜎
            { new int[] { 0x1D70F }, "t"}, // 𝜏
            { new int[] { 0x1D710 }, "y"}, // 𝜐
            { new int[] { 0x1D711 }, "f"}, // 𝜑
            { new int[] { 0x1D712 }, "x"}, // 𝜒
            { new int[] { 0x1D713 }, "ps"}, // 𝜓
            { new int[] { 0x1D714 }, "o"}, // 𝜔
            { new int[] { 0x1D715 }, "d"}, // 𝜕
            { new int[] { 0x1D716 }, "E"}, // 𝜖
            { new int[] { 0x1D717 }, "TH"}, // 𝜗
            { new int[] { 0x1D718 }, "K"}, // 𝜘
            { new int[] { 0x1D719 }, "f"}, // 𝜙
            { new int[] { 0x1D71A }, "r"}, // 𝜚
            { new int[] { 0x1D71B }, "p"}, // 𝜛
            { new int[] { 0x1D71C }, "A"}, // 𝜜
            { new int[] { 0x1D71D }, "V"}, // 𝜝
            { new int[] { 0x1D71E }, "G"}, // 𝜞
            { new int[] { 0x1D71F }, "D"}, // 𝜟
            { new int[] { 0x1D720 }, "E"}, // 𝜠
            { new int[] { 0x1D721 }, "Z"}, // 𝜡
            { new int[] { 0x1D722 }, "I"}, // 𝜢
            { new int[] { 0x1D723 }, "TH"}, // 𝜣
            { new int[] { 0x1D724 }, "I"}, // 𝜤
            { new int[] { 0x1D725 }, "K"}, // 𝜥
            { new int[] { 0x1D726 }, "L"}, // 𝜦
            { new int[] { 0x1D727 }, "M"}, // 𝜧
            { new int[] { 0x1D728 }, "N"}, // 𝜨
            { new int[] { 0x1D729 }, "KS"}, // 𝜩
            { new int[] { 0x1D72A }, "O"}, // 𝜪
            { new int[] { 0x1D72B }, "P"}, // 𝜫
            { new int[] { 0x1D72C }, "S"}, // 𝜬
            { new int[] { 0x1D72D }, "TH"}, // 𝜭
            { new int[] { 0x1D72E }, "S"}, // 𝜮
            { new int[] { 0x1D72F }, "T"}, // 𝜯
            { new int[] { 0x1D730 }, "Y"}, // 𝜰
            { new int[] { 0x1D731 }, "F"}, // 𝜱
            { new int[] { 0x1D732 }, "X"}, // 𝜲
            { new int[] { 0x1D733 }, "PS"}, // 𝜳
            { new int[] { 0x1D734 }, "O"}, // 𝜴
            { new int[] { 0x1D735 }, "D"}, // 𝜵
            { new int[] { 0x1D736 }, "a"}, // 𝜶
            { new int[] { 0x1D737 }, "v"}, // 𝜷
            { new int[] { 0x1D738 }, "g"}, // 𝜸
            { new int[] { 0x1D739 }, "d"}, // 𝜹
            { new int[] { 0x1D73A }, "e"}, // 𝜺
            { new int[] { 0x1D73B }, "z"}, // 𝜻
            { new int[] { 0x1D73C }, "i"}, // 𝜼
            { new int[] { 0x1D73D }, "th"}, // 𝜽
            { new int[] { 0x1D73E }, "i"}, // 𝜾
            { new int[] { 0x1D73F }, "k"}, // 𝜿
            { new int[] { 0x1D740 }, "l"}, // 𝝀
            { new int[] { 0x1D741 }, "m"}, // 𝝁
            { new int[] { 0x1D742 }, "n"}, // 𝝂
            { new int[] { 0x1D743 }, "ks"}, // 𝝃
            { new int[] { 0x1D744 }, "o"}, // 𝝄
            { new int[] { 0x1D745 }, "p"}, // 𝝅
            { new int[] { 0x1D746 }, "r"}, // 𝝆
            { new int[] { 0x1D747 }, "s"}, // 𝝇
            { new int[] { 0x1D748 }, "s"}, // 𝝈
            { new int[] { 0x1D749 }, "t"}, // 𝝉
            { new int[] { 0x1D74A }, "y"}, // 𝝊
            { new int[] { 0x1D74B }, "f"}, // 𝝋
            { new int[] { 0x1D74C }, "x"}, // 𝝌
            { new int[] { 0x1D74D }, "ps"}, // 𝝍
            { new int[] { 0x1D74E }, "o"}, // 𝝎
            { new int[] { 0x1D74F }, "a"}, // 𝝏
            { new int[] { 0x1D750 }, "e"}, // 𝝐
            { new int[] { 0x1D751 }, "i"}, // 𝝑
            { new int[] { 0x1D752 }, "k"}, // 𝝒
            { new int[] { 0x1D753 }, "f"}, // 𝝓
            { new int[] { 0x1D754 }, "r"}, // 𝝔
            { new int[] { 0x1D755 }, "p"}, // 𝝕
            { new int[] { 0x1D756 }, "A"}, // 𝝖
            { new int[] { 0x1D757 }, "B"}, // 𝝗
            { new int[] { 0x1D758 }, "G"}, // 𝝘
            { new int[] { 0x1D759 }, "D"}, // 𝝙
            { new int[] { 0x1D75A }, "E"}, // 𝝚
            { new int[] { 0x1D75B }, "Z"}, // 𝝛
            { new int[] { 0x1D75C }, "I"}, // 𝝜
            { new int[] { 0x1D75D }, "TH"}, // 𝝝
            { new int[] { 0x1D75E }, "I"}, // 𝝞
            { new int[] { 0x1D75F }, "K"}, // 𝝟
            { new int[] { 0x1D760 }, "L"}, // 𝝠
            { new int[] { 0x1D761 }, "M"}, // 𝝡
            { new int[] { 0x1D762 }, "N"}, // 𝝢
            { new int[] { 0x1D763 }, "KS"}, // 𝝣
            { new int[] { 0x1D764 }, "O"}, // 𝝤
            { new int[] { 0x1D765 }, "P"}, // 𝝥
            { new int[] { 0x1D766 }, "R"}, // 𝝦
            { new int[] { 0x1D767 }, "TH"}, // 𝝧
            { new int[] { 0x1D768 }, "S"}, // 𝝨
            { new int[] { 0x1D769 }, "T"}, // 𝝩
            { new int[] { 0x1D76A }, "Y"}, // 𝝪
            { new int[] { 0x1D76B }, "F"}, // 𝝫
            { new int[] { 0x1D76C }, "X"}, // 𝝬
            { new int[] { 0x1D76D }, "PS"}, // 𝝭
            { new int[] { 0x1D76E }, "O"}, // 𝝮
            { new int[] { 0x1D76F }, "D"}, // 𝝯
            { new int[] { 0x1D770 }, "a"}, // 𝝰
            { new int[] { 0x1D771 }, "v"}, // 𝝱
            { new int[] { 0x1D772 }, "g"}, // 𝝲
            { new int[] { 0x1D773 }, "d"}, // 𝝳
            { new int[] { 0x1D774 }, "e"}, // 𝝴
            { new int[] { 0x1D775 }, "z"}, // 𝝵
            { new int[] { 0x1D776 }, "i"}, // 𝝶
            { new int[] { 0x1D777 }, "th"}, // 𝝷
            { new int[] { 0x1D778 }, "i"}, // 𝝸
            { new int[] { 0x1D779 }, "k"}, // 𝝹
            { new int[] { 0x1D77A }, "l"}, // 𝝺
            { new int[] { 0x1D77B }, "m"}, // 𝝻
            { new int[] { 0x1D77C }, "n"}, // 𝝼
            { new int[] { 0x1D77D }, "ks"}, // 𝝽
            { new int[] { 0x1D77E }, "o"}, // 𝝾
            { new int[] { 0x1D77F }, "p"}, // 𝝿
            { new int[] { 0x1D780 }, "r"}, // 𝞀
            { new int[] { 0x1D781 }, "s"}, // 𝞁
            { new int[] { 0x1D782 }, "s"}, // 𝞂
            { new int[] { 0x1D783 }, "t"}, // 𝞃
            { new int[] { 0x1D784 }, "y"}, // 𝞄
            { new int[] { 0x1D785 }, "f"}, // 𝞅
            { new int[] { 0x1D786 }, "x"}, // 𝞆
            { new int[] { 0x1D787 }, "ps"}, // 𝞇
            { new int[] { 0x1D788 }, "o"}, // 𝞈
            { new int[] { 0x1D789 }, "a"}, // 𝞉
            { new int[] { 0x1D78A }, "e"}, // 𝞊
            { new int[] { 0x1D78B }, "i"}, // 𝞋
            { new int[] { 0x1D78C }, "k"}, // 𝞌
            { new int[] { 0x1D78D }, "f"}, // 𝞍
            { new int[] { 0x1D78E }, "r"}, // 𝞎
            { new int[] { 0x1D78F }, "p"}, // 𝞏
            { new int[] { 0x1D790 }, "A"}, // 𝞐
            { new int[] { 0x1D791 }, "V"}, // 𝞑
            { new int[] { 0x1D792 }, "G"}, // 𝞒
            { new int[] { 0x1D793 }, "D"}, // 𝞓
            { new int[] { 0x1D794 }, "E"}, // 𝞔
            { new int[] { 0x1D795 }, "Z"}, // 𝞕
            { new int[] { 0x1D796 }, "I"}, // 𝞖
            { new int[] { 0x1D797 }, "TH"}, // 𝞗
            { new int[] { 0x1D798 }, "I"}, // 𝞘
            { new int[] { 0x1D799 }, "K"}, // 𝞙
            { new int[] { 0x1D79A }, "L"}, // 𝞚
            { new int[] { 0x1D79B }, "M"}, // 𝞛
            { new int[] { 0x1D79C }, "N"}, // 𝞜
            { new int[] { 0x1D79D }, "KS"}, // 𝞝
            { new int[] { 0x1D79E }, "O"}, // 𝞞
            { new int[] { 0x1D79F }, "P"}, // 𝞟
            { new int[] { 0x1D7A0 }, "S"}, // 𝞠
            { new int[] { 0x1D7A1 }, "TH"}, // 𝞡
            { new int[] { 0x1D7A2 }, "S"}, // 𝞢
            { new int[] { 0x1D7A3 }, "T"}, // 𝞣
            { new int[] { 0x1D7A4 }, "Y"}, // 𝞤
            { new int[] { 0x1D7A5 }, "F"}, // 𝞥
            { new int[] { 0x1D7A6 }, "X"}, // 𝞦
            { new int[] { 0x1D7A7 }, "PS"}, // 𝞧
            { new int[] { 0x1D7A8 }, "O"}, // 𝞨
            { new int[] { 0x1D7A9 }, "D"}, // 𝞩
            { new int[] { 0x1D7AA }, "av"}, // 𝞪
            { new int[] { 0x1D7AB }, "g"}, // 𝞫
            { new int[] { 0x1D7AC }, "d"}, // 𝞬
            { new int[] { 0x1D7AD }, "e"}, // 𝞭
            { new int[] { 0x1D7AE }, "z"}, // 𝞮
            { new int[] { 0x1D7AF }, "i"}, // 𝞯
            { new int[] { 0x1D7B0 }, "i"}, // 𝞰
            { new int[] { 0x1D7B1 }, "th"}, // 𝞱
            { new int[] { 0x1D7B2 }, "i"}, // 𝞲
            { new int[] { 0x1D7B3 }, "k"}, // 𝞳
            { new int[] { 0x1D7B4 }, "l"}, // 𝞴
            { new int[] { 0x1D7B5 }, "m"}, // 𝞵
            { new int[] { 0x1D7B6 }, "n"}, // 𝞶
            { new int[] { 0x1D7B7 }, "ks"}, // 𝞷
            { new int[] { 0x1D7B8 }, "o"}, // 𝞸
            { new int[] { 0x1D7B9 }, "p"}, // 𝞹
            { new int[] { 0x1D7BA }, "r"}, // 𝞺
            { new int[] { 0x1D7BB }, "s"}, // 𝞻
            { new int[] { 0x1D7BC }, "s"}, // 𝞼
            { new int[] { 0x1D7BD }, "t"}, // 𝞽
            { new int[] { 0x1D7BE }, "y"}, // 𝞾
            { new int[] { 0x1D7BF }, "f"}, // 𝞿
            { new int[] { 0x1D7C0 }, "x"}, // 𝟀
            { new int[] { 0x1D7C1 }, "ps"}, // 𝟁
            { new int[] { 0x1D7C2 }, "o"}, // 𝟂
            { new int[] { 0x1D7C3 }, "a"}, // 𝟃
            { new int[] { 0x1D7C4 }, "e"}, // 𝟄
            { new int[] { 0x1D7C5 }, "i"}, // 𝟅
            { new int[] { 0x1D7C6 }, "k"}, // 𝟆
            { new int[] { 0x1D7C7 }, "f"}, // 𝟇
            { new int[] { 0x1D7C8 }, "r"}, // 𝟈
            { new int[] { 0x1D7C9 }, "p"}, // 𝟉
            { new int[] { 0x1D7CA }, "F"}, // 𝟊
            { new int[] { 0x1D7CB }, "f"}, // 𝟋
            { new int[] { 0x249C }, "(a)"}, // ⒜
            { new int[] { 0x249D }, "(b)"}, // ⒝
            { new int[] { 0x249E }, "(c)"}, // ⒞
            { new int[] { 0x249F }, "(d)"}, // ⒟
            { new int[] { 0x24A0 }, "(e)"}, // ⒠
            { new int[] { 0x24A1 }, "(f)"}, // ⒡
            { new int[] { 0x24A2 }, "(g)"}, // ⒢
            { new int[] { 0x24A3 }, "(h)"}, // ⒣
            { new int[] { 0x24A4 }, "(i)"}, // ⒤
            { new int[] { 0x24A5 }, "(j)"}, // ⒥
            { new int[] { 0x24A6 }, "(k)"}, // ⒦
            { new int[] { 0x24A7 }, "(l)"}, // ⒧
            { new int[] { 0x24A8 }, "(m)"}, // ⒨
            { new int[] { 0x24A9 }, "(n)"}, // ⒩
            { new int[] { 0x24AA }, "(o)"}, // ⒪
            { new int[] { 0x24AB }, "(p)"}, // ⒫
            { new int[] { 0x24AC }, "(q)"}, // ⒬
            { new int[] { 0x24AD }, "(r)"}, // ⒭
            { new int[] { 0x24AE }, "(s)"}, // ⒮
            { new int[] { 0x24AF }, "(t)"}, // ⒯
            { new int[] { 0x24B0 }, "(u)"}, // ⒰
            { new int[] { 0x24B1 }, "(v)"}, // ⒱
            { new int[] { 0x24B2 }, "(w)"}, // ⒲
            { new int[] { 0x24B3 }, "(x)"}, // ⒳
            { new int[] { 0x24B4 }, "(y)"}, // ⒴
            { new int[] { 0x24B5 }, "(z)"}, // ⒵
            { new int[] { 0x24B6 }, "(A)"}, // Ⓐ
            { new int[] { 0x24B7 }, "(B)"}, // Ⓑ
            { new int[] { 0x24B8 }, "(C)"}, // Ⓒ
            { new int[] { 0x24B9 }, "(D)"}, // Ⓓ
            { new int[] { 0x24BA }, "(E)"}, // Ⓔ
            { new int[] { 0x24BB }, "(F)"}, // Ⓕ
            { new int[] { 0x24BC }, "(G)"}, // Ⓖ
            { new int[] { 0x24BD }, "(H)"}, // Ⓗ
            { new int[] { 0x24BE }, "(I)"}, // Ⓘ
            { new int[] { 0x24BF }, "(J)"}, // Ⓙ
            { new int[] { 0x24C0 }, "(K)"}, // Ⓚ
            { new int[] { 0x24C1 }, "(L)"}, // Ⓛ
            { new int[] { 0x24C3 }, "(N)"}, // Ⓝ
            { new int[] { 0x24C4 }, "(O)"}, // Ⓞ
            { new int[] { 0x24C5 }, "(P)"}, // Ⓟ
            { new int[] { 0x24C6 }, "(Q)"}, // Ⓠ
            { new int[] { 0x24C7 }, "(R)"}, // Ⓡ
            { new int[] { 0x24C8 }, "(S)"}, // Ⓢ
            { new int[] { 0x24C9 }, "(T)"}, // Ⓣ
            { new int[] { 0x24CA }, "(U)"}, // Ⓤ
            { new int[] { 0x24CB }, "(V)"}, // Ⓥ
            { new int[] { 0x24CC }, "(W)"}, // Ⓦ
            { new int[] { 0x24CD }, "(X)"}, // Ⓧ
            { new int[] { 0x24CE }, "(Y)"}, // Ⓨ
            { new int[] { 0x24CF }, "(Z)"}, // Ⓩ
            { new int[] { 0x24D0 }, "(a)"}, // ⓐ
            { new int[] { 0x24D1 }, "(b)"}, // ⓑ
            { new int[] { 0x24D2 }, "(b)"}, // ⓒ
            { new int[] { 0x24D3 }, "(c)"}, // ⓓ
            { new int[] { 0x24D4 }, "(e)"}, // ⓔ
            { new int[] { 0x24D5 }, "(f)"}, // ⓕ
            { new int[] { 0x24D6 }, "(g)"}, // ⓖ
            { new int[] { 0x24D7 }, "(h)"}, // ⓗ
            { new int[] { 0x24D8 }, "(i)"}, // ⓘ
            { new int[] { 0x24D9 }, "(j)"}, // ⓙ
            { new int[] { 0x24DA }, "(k)"}, // ⓚ
            { new int[] { 0x24DB }, "(l)"}, // ⓛ
            { new int[] { 0x24DC }, "(m)"}, // ⓜ
            { new int[] { 0x24DD }, "(n)"}, // ⓝ
            { new int[] { 0x24DE }, "(o)"}, // ⓞ
            { new int[] { 0x24DF }, "(p)"}, // ⓟ
            { new int[] { 0x24E0 }, "(q)"}, // ⓠ
            { new int[] { 0x24E1 }, "(r)"}, // ⓡ
            { new int[] { 0x24E2 }, "(s)"}, // ⓢ
            { new int[] { 0x24E3 }, "(t)"}, // ⓣ
            { new int[] { 0x24E4 }, "(u)"}, // ⓤ
            { new int[] { 0x24E5 }, "(v)"}, // ⓥ
            { new int[] { 0x24E6 }, "(w)"}, // ⓦ
            { new int[] { 0x24E7 }, "(x)"}, // ⓧ
            { new int[] { 0x24E8 }, "(y)"}, // ⓨ
            { new int[] { 0x24E9 }, "(z)"}, // ⓩ

            // Maltese
            { new int[] { 0x10A }, "C"}, // Ċ
            { new int[] { 0x10B }, "c"}, // ċ
            { new int[] { 0x120 }, "G"}, // Ġ
            { new int[] { 0x121 }, "g"}, // ġ
            { new int[] { 0x126 }, "H"}, // Ħ
            { new int[] { 0x127 }, "h"}, // ħ

            // Numbers
            { new int[] { 0x1D7CE }, "0"}, // 𝟎
            { new int[] { 0x1D7CF }, "1"}, // 𝟏
            { new int[] { 0x1D7D0 }, "2"}, // 𝟐
            { new int[] { 0x1D7D1 }, "3"}, // 𝟑
            { new int[] { 0x1D7D2 }, "4"}, // 𝟒
            { new int[] { 0x1D7D3 }, "5"}, // 𝟓
            { new int[] { 0x1D7D4 }, "6"}, // 𝟔
            { new int[] { 0x1D7D5 }, "7"}, // 𝟕
            { new int[] { 0x1D7D6 }, "8"}, // 𝟖
            { new int[] { 0x1D7D7 }, "9"}, // 𝟗
            { new int[] { 0x1D7D8 }, "0"}, // 𝟘
            { new int[] { 0x1D7D9 }, "1"}, // 𝟙
            { new int[] { 0x1D7DA }, "2"}, // 𝟚
            { new int[] { 0x1D7DB }, "3"}, // 𝟛
            { new int[] { 0x1D7DC }, "4"}, // 𝟜
            { new int[] { 0x1D7DD }, "5"}, // 𝟝
            { new int[] { 0x1D7DE }, "6"}, // 𝟞
            { new int[] { 0x1D7DF }, "7"}, // 𝟟
            { new int[] { 0x1D7E0 }, "8"}, // 𝟠
            { new int[] { 0x1D7E1 }, "9"}, // 𝟡
            { new int[] { 0x1D7E2 }, "0"}, // 𝟢
            { new int[] { 0x1D7E3 }, "1"}, // 𝟣
            { new int[] { 0x1D7E4 }, "2"}, // 𝟤
            { new int[] { 0x1D7E5 }, "3"}, // 𝟥
            { new int[] { 0x1D7E6 }, "4"}, // 𝟦
            { new int[] { 0x1D7E7 }, "5"}, // 𝟧
            { new int[] { 0x1D7E8 }, "6"}, // 𝟨
            { new int[] { 0x1D7E9 }, "7"}, // 𝟩
            { new int[] { 0x1D7EA }, "8"}, // 𝟪
            { new int[] { 0x1D7EB }, "9"}, // 𝟫
            { new int[] { 0x1D7EC }, "0"}, // 𝟬
            { new int[] { 0x1D7ED }, "1"}, // 𝟭
            { new int[] { 0x1D7EE }, "2"}, // 𝟮
            { new int[] { 0x1D7EF }, "3"}, // 𝟯
            { new int[] { 0x1D7F0 }, "4"}, // 𝟰
            { new int[] { 0x1D7F1 }, "5"}, // 𝟱
            { new int[] { 0x1D7F2 }, "6"}, // 𝟲
            { new int[] { 0x1D7F3 }, "7"}, // 𝟳
            { new int[] { 0x1D7F4 }, "8"}, // 𝟴
            { new int[] { 0x1D7F5 }, "9"}, // 𝟵
            { new int[] { 0x1D7F6 }, "0"}, // 𝟶
            { new int[] { 0x1D7F7 }, "1"}, // 𝟷
            { new int[] { 0x1D7F8 }, "2"}, // 𝟸
            { new int[] { 0x1D7F9 }, "3"}, // 𝟹
            { new int[] { 0x1D7FA }, "4"}, // 𝟺
            { new int[] { 0x1D7FB }, "5"}, // 𝟻
            { new int[] { 0x1D7FC }, "6"}, // 𝟼
            { new int[] { 0x1D7FD }, "7"}, // 𝟽
            { new int[] { 0x1D7FE }, "8"}, // 𝟾
            { new int[] { 0x1D7FF }, "9"}, // 𝟿
            { new int[] { 0x2460 }, "1"}, // ①
            { new int[] { 0x2461 }, "2"}, // ②
            { new int[] { 0x2462 }, "3"}, // ③
            { new int[] { 0x2463 }, "4"}, // ④
            { new int[] { 0x2464 }, "5"}, // ⑤
            { new int[] { 0x2465 }, "6"}, // ⑥
            { new int[] { 0x2466 }, "7"}, // ⑦
            { new int[] { 0x2467 }, "8"}, // ⑧
            { new int[] { 0x2468 }, "9"}, // ⑨
            { new int[] { 0x2469 }, "10"}, // ⑩
            { new int[] { 0x246A }, "11"}, // ⑪
            { new int[] { 0x246B }, "12"}, // ⑫
            { new int[] { 0x246C }, "13"}, // ⑬
            { new int[] { 0x246D }, "14"}, // ⑭
            { new int[] { 0x246E }, "15"}, // ⑮
            { new int[] { 0x246F }, "16"}, // ⑯
            { new int[] { 0x2470 }, "17"}, // ⑰
            { new int[] { 0x2471 }, "18"}, // ⑱
            { new int[] { 0x2472 }, "19"}, // ⑲
            { new int[] { 0x2473 }, "20"}, // ⑳
            { new int[] { 0x2474 }, "1"}, // ⑴
            { new int[] { 0x2475 }, "2"}, // ⑵
            { new int[] { 0x2476 }, "3"}, // ⑶
            { new int[] { 0x2477 }, "4"}, // ⑷
            { new int[] { 0x2478 }, "5"}, // ⑸
            { new int[] { 0x2479 }, "6"}, // ⑹
            { new int[] { 0x247A }, "7"}, // ⑺
            { new int[] { 0x247B }, "8"}, // ⑻
            { new int[] { 0x247C }, "9"}, // ⑼
            { new int[] { 0x247D }, "10"}, // ⑽
            { new int[] { 0x247E }, "11"}, // ⑾
            { new int[] { 0x247F }, "12"}, // ⑿
            { new int[] { 0x2480 }, "13"}, // ⒀
            { new int[] { 0x2481 }, "14"}, // ⒁
            { new int[] { 0x2482 }, "15"}, // ⒂
            { new int[] { 0x2483 }, "16"}, // ⒃
            { new int[] { 0x2484 }, "17"}, // ⒄
            { new int[] { 0x2485 }, "18"}, // ⒅
            { new int[] { 0x2486 }, "19"}, // ⒆
            { new int[] { 0x2487 }, "20"}, // ⒇
            { new int[] { 0x2488 }, "1."}, // ⒈
            { new int[] { 0x2489 }, "2."}, // ⒉
            { new int[] { 0x248A }, "3."}, // ⒊
            { new int[] { 0x248B }, "4."}, // ⒋
            { new int[] { 0x248C }, "5."}, // ⒌
            { new int[] { 0x248D }, "6."}, // ⒍
            { new int[] { 0x248E }, "7."}, // ⒎
            { new int[] { 0x248F }, "8."}, // ⒏
            { new int[] { 0x2490 }, "9."}, // ⒐
            { new int[] { 0x2491 }, "10."}, // ⒑
            { new int[] { 0x2492 }, "11."}, // ⒒
            { new int[] { 0x2493 }, "12."}, // ⒓
            { new int[] { 0x2494 }, "13."}, // ⒔
            { new int[] { 0x2495 }, "14."}, // ⒕
            { new int[] { 0x2496 }, "15."}, // ⒖
            { new int[] { 0x2497 }, "16."}, // ⒗
            { new int[] { 0x2498 }, "17."}, // ⒘
            { new int[] { 0x2499 }, "18."}, // ⒙
            { new int[] { 0x249A }, "19."}, // ⒚
            { new int[] { 0x249B }, "20."}, // ⒛
            { new int[] { 0x24EA }, "0"}, // ⓪
            { new int[] { 0x24EB }, "11"}, // ⓫
            { new int[] { 0x24EC }, "12"}, // ⓬
            { new int[] { 0x24ED }, "13"}, // ⓭
            { new int[] { 0x24EE }, "14"}, // ⓮
            { new int[] { 0x24EF }, "15"}, // ⓯
            { new int[] { 0x24F0 }, "16"}, // ⓰
            { new int[] { 0x24F1 }, "17"}, // ⓱
            { new int[] { 0x24F2 }, "18"}, // ⓲
            { new int[] { 0x24F3 }, "19"}, // ⓳
            { new int[] { 0x24F4 }, "20"}, // ⓴
            { new int[] { 0x24F5 }, "1"}, // ⓵
            { new int[] { 0x24F6 }, "2"}, // ⓶
            { new int[] { 0x24F7 }, "3"}, // ⓷
            { new int[] { 0x24F8 }, "4"}, // ⓸
            { new int[] { 0x24F9 }, "5"}, // ⓹
            { new int[] { 0x24FA }, "6"}, // ⓺
            { new int[] { 0x24FB }, "7"}, // ⓻
            { new int[] { 0x24FC }, "8"}, // ⓼
            { new int[] { 0x24FD }, "9"}, // ⓽
            { new int[] { 0x24FE }, "10"}, // ⓾
            { new int[] { 0x24FF }, "0"}, // ⓿

            // Punctuation
            { new int[] { 0x1F670 }, "&"}, // 🙰
            { new int[] { 0x1F671 }, "&"}, // 🙱
            { new int[] { 0x1F672 }, "&"}, // 🙲
            { new int[] { 0x1F673 }, "&"}, // 🙳
            { new int[] { 0x1F674 }, "&"}, // 🙴
            { new int[] { 0x1F675 }, "&"}, // 🙵
            { new int[] { 0x1F676 }, "\""}, // 🙶
            { new int[] { 0x1F677 }, "\""}, // 🙷
            { new int[] { 0x1F678 }, "\""}, // 🙸
            { new int[] { 0x203D }, "?!"}, // ‽
            { new int[] { 0x1F679 }, "?!"}, // 🙹
            { new int[] { 0x1F67A }, "?!"}, // 🙺
            { new int[] { 0x1F67B }, "?!"}, // 🙻
            { new int[] { 0x1F67C }, "/"},  // 🙼
            { new int[] { 0x1F67D }, "\\"}, // 🙽

            // Alchemy
            { new int[] { 0x1F707 }, "AR"}, // 🜇
            { new int[] { 0x1F708 }, "V"}, // 🜈
            { new int[] { 0x1F709 }, "V"}, // 🜉
            { new int[] { 0x1F706 }, "VR"}, // 🜆
            { new int[] { 0x1F705 }, "VF"}, // 🜅
            { new int[] { 0x1F729 }, "2"}, // 🜩
            { new int[] { 0x1F72A }, "5"}, // 🜪
            { new int[] { 0x1F761 }, "f"}, // 🝡
            { new int[] { 0x1F762 }, "W"}, // 🝢
            { new int[] { 0x1F763 }, "U"}, // 🝣
            { new int[] { 0x1F767 }, "V"}, // 🝧
            { new int[] { 0x1F768 }, "T"}, // 🝨
            { new int[] { 0x1F76A }, "V"}, // 🝪
            { new int[] { 0x1F76B }, "MB"}, // 🝫
            { new int[] { 0x1F76C }, "VB"}, // 🝬
            { new int[] { 0x1F772 }, "3B"}, // 🝲
            { new int[] { 0x1F773 }, "3B"}, // 🝳

            { new int[] { 0x1CD }, "A"}, // Ǎ
            { new int[] { 0x200 }, "A"}, // Ȁ
            { new int[] { 0x202 }, "A"}, // Ȃ
            { new int[] { 0x226 }, "A"}, // Ȧ
            { new int[] { 0x1CE }, "a"}, // ǎ
            { new int[] { 0x201 }, "a"}, // ȁ
            { new int[] { 0x203 }, "a"}, // ȃ
            { new int[] { 0x227 }, "a"}, // ȧ
            { new int[] { 0x180 }, "b"}, // ƀ
            { new int[] { 0x183 }, "b"}, // ƃ
            { new int[] { 0x108 }, "C"}, // Ĉ
            { new int[] { 0x109 }, "c"}, // ĉ
            { new int[] { 0x1E0C }, "D"}, // Ḍ
            { new int[] { 0x1E10 }, "D"}, // Ḑ
            { new int[] { 0x1E12 }, "D"}, // Ḓ
            { new int[] { 0x1E0D }, "d"}, // ḍ
            { new int[] { 0x1E11 }, "d"}, // ḑ
            { new int[] { 0x1E13 }, "d"}, // ḓ
            { new int[] { 0x204 }, "E"}, // Ȅ
            { new int[] { 0x206 }, "E"}, // Ȇ
            { new int[] { 0x228 }, "E"}, // Ȩ
            { new int[] { 0x115 }, "e"}, // ĕ
            { new int[] { 0x205 }, "e"}, // ȅ
            { new int[] { 0x207 }, "e"}, // ȇ
            { new int[] { 0x229 }, "e"}, // ȩ
            { new int[] { 0x192 }, "f"}, // ƒ
            { new int[] { 0x11C }, "G"}, // Ĝ
            { new int[] { 0x1E6 }, "G"}, // Ǧ
            { new int[] { 0x1F4 }, "G"}, // Ǵ
            { new int[] { 0x11D }, "g"}, // ĝ
            { new int[] { 0x1E7 }, "g"}, // ǧ
            { new int[] { 0x1F5 }, "g"}, // ǵ
            { new int[] { 0x124 }, "H"}, // Ĥ
            { new int[] { 0x21E }, "H"}, // Ȟ
            { new int[] { 0x1E24 }, "H"}, // Ḥ
            { new int[] { 0x1E26 }, "H"}, // Ḧ
            { new int[] { 0x1E28 }, "H"}, // Ḩ
            { new int[] { 0x1E2A }, "H"}, // Ḫ
            { new int[] { 0x125 }, "h"}, // ĥ
            { new int[] { 0x21F }, "h"}, // ȟ
            { new int[] { 0x1E25 }, "h"}, // ḥ
            { new int[] { 0x1E27 }, "h"}, // ḧ
            { new int[] { 0x1E29 }, "h"}, // ḩ
            { new int[] { 0x1E2B }, "h"}, // ḫ
            { new int[] { 0x12C }, "I"}, // Ĭ
            { new int[] { 0x1CF }, "I"}, // Ǐ
            { new int[] { 0x208 }, "I"}, // Ȉ
            { new int[] { 0x20A }, "I"}, // Ȋ
            { new int[] { 0x12D }, "i"}, // ĭ
            { new int[] { 0x1D0 }, "i"}, // ǐ
            { new int[] { 0x209 }, "i"}, // ȉ
            { new int[] { 0x20B }, "i"}, // ȋ
            { new int[] { 0x134 }, "J"}, // Ĵ
            { new int[] { 0x135 }, "j"}, // ĵ
            { new int[] { 0x1E8 }, "K"}, // Ǩ
            { new int[] { 0x1E30 }, "K"}, // Ḱ
            { new int[] { 0x1E32 }, "K"}, // Ḳ
            { new int[] { 0x1E34 }, "K"}, // Ḵ
            { new int[] { 0x1E9 }, "k"}, // ǩ
            { new int[] { 0x1E31 }, "k"}, // ḱ
            { new int[] { 0x1E33 }, "k"}, // ḳ
            { new int[] { 0x1E35 }, "k"}, // ḵ
            { new int[] { 0x139 }, "L"}, // Ĺ
            { new int[] { 0x13D }, "L"}, // Ľ
            { new int[] { 0x13F }, "L"}, // Ŀ
            { new int[] { 0x13A }, "l"}, // ĺ
            { new int[] { 0x13E }, "l"}, // ľ
            { new int[] { 0x140 }, "l"}, // ŀ
            { new int[] { 0x1E3E }, "M"}, // Ḿ
            { new int[] { 0x1E40 }, "M"}, // Ṁ
            { new int[] { 0x1E42 }, "M"}, // Ṃ
            { new int[] { 0x1E3F }, "m"}, // ḿ
            { new int[] { 0x1E41 }, "m"}, // ṁ
            { new int[] { 0x1E43 }, "m"}, // ṃ
            { new int[] { 0x14A }, "N"}, // Ŋ
            { new int[] { 0x1E44 }, "N"}, // Ṅ
            { new int[] { 0x1E46 }, "N"}, // Ṇ
            { new int[] { 0x1E48 }, "N"}, // Ṉ
            { new int[] { 0x1E4A }, "N"}, // Ṋ
            { new int[] { 0x14B }, "n"}, // ŋ
            { new int[] { 0x1E45 }, "n"}, // ṅ
            { new int[] { 0x1E47 }, "n"}, // ṇ
            { new int[] { 0x1E49 }, "n"}, // ṉ
            { new int[] { 0x1E4B }, "n"}, // ṋ
            { new int[] { 0x14C }, "O"}, // Ō
            { new int[] { 0x14E }, "O"}, // Ŏ
            { new int[] { 0x1D1 }, "O"}, // Ǒ
            { new int[] { 0x20C }, "O"}, // Ȍ
            { new int[] { 0x20E }, "O"}, // Ȏ
            { new int[] { 0x22A }, "O"}, // Ȫ
            { new int[] { 0x22C }, "O"}, // Ȭ
            { new int[] { 0x22E }, "O"}, // Ȯ
            { new int[] { 0x230 }, "O"}, // Ȱ
            { new int[] { 0x14D }, "o"}, // ō
            { new int[] { 0x14F }, "o"}, // ŏ
            { new int[] { 0x1D2 }, "o"}, // ǒ
            { new int[] { 0x20D }, "o"}, // ȍ
            { new int[] { 0x20F }, "o"}, // ȏ
            { new int[] { 0x22B }, "o"}, // ȫ
            { new int[] { 0x22D }, "o"}, // ȭ
            { new int[] { 0x22F }, "o"}, // ȯ
            { new int[] { 0x231 }, "o"}, // ȱ
            { new int[] { 0x1E54 }, "P"}, // Ṕ
            { new int[] { 0x1E56 }, "P"}, // Ṗ
            { new int[] { 0x1E55 }, "p"}, // ṕ
            { new int[] { 0x1E57 }, "p"}, // ṗ
            { new int[] { 0x154 }, "R"}, // Ŕ
            { new int[] { 0x156 }, "R"}, // Ŗ
            { new int[] { 0x210 }, "R"}, // Ȑ
            { new int[] { 0x212 }, "R"}, // Ȓ
            { new int[] { 0x1E58 }, "R"}, // Ṙ
            { new int[] { 0x1E5A }, "R"}, // Ṛ
            { new int[] { 0x1E5E }, "R"}, // Ṟ
            { new int[] { 0x155 }, "r"}, // ŕ
            { new int[] { 0x157 }, "r"}, // ŗ
            { new int[] { 0x211 }, "r"}, // ȑ
            { new int[] { 0x213 }, "r"}, // ȓ
            { new int[] { 0x1E59 }, "r"}, // ṙ
            { new int[] { 0x1E5B }, "r"}, // ṛ
            { new int[] { 0x1E5F }, "r"}, // ṟ
            { new int[] { 0x15C }, "S"}, // Ŝ
            { new int[] { 0x1E60 }, "S"}, // Ṡ
            { new int[] { 0x1E62 }, "S"}, // Ṣ
            { new int[] { 0x15D }, "s"}, // ŝ
            { new int[] { 0x1E61 }, "s"}, // ṡ
            { new int[] { 0x1E63 }, "s"}, // ṣ
            { new int[] { 0x166 }, "T"}, // Ŧ
            { new int[] { 0x1E6A }, "T"}, // Ṫ
            { new int[] { 0x1E6C }, "T"}, // Ṭ
            { new int[] { 0x1E6E }, "T"}, // Ṯ
            { new int[] { 0x1E70 }, "T"}, // Ṱ
            { new int[] { 0x167 }, "t"}, // ŧ
            { new int[] { 0x1E6B }, "t"}, // ṫ
            { new int[] { 0x1E6D }, "t"}, // ṭ
            { new int[] { 0x1E6F }, "t"}, // ṯ
            { new int[] { 0x1E71 }, "t"}, // ṱ
            { new int[] { 0x16C }, "U"}, // Ŭ
            { new int[] { 0x1D3 }, "U"}, // Ǔ
            { new int[] { 0x214 }, "U"}, // Ȕ
            { new int[] { 0x216 }, "U"}, // Ȗ
            { new int[] { 0x16D }, "u"}, // ŭ
            { new int[] { 0x1D4 }, "u"}, // ǔ
            { new int[] { 0x215 }, "u"}, // ȕ
            { new int[] { 0x217 }, "u"}, // ȗ
            { new int[] { 0x1E7C }, "V"}, // Ṽ
            { new int[] { 0x1E7E }, "V"}, // Ṿ
            { new int[] { 0x1E7D }, "v"}, // ṽ
            { new int[] { 0x1E7F }, "v"}, // ṿ
            { new int[] { 0x174 }, "W"}, // Ŵ
            { new int[] { 0x1E80 }, "W"}, // Ẁ
            { new int[] { 0x1E82 }, "W"}, // Ẃ
            { new int[] { 0x1E84 }, "W"}, // Ẅ
            { new int[] { 0x1E86 }, "W"}, // Ẇ
            { new int[] { 0x1E88 }, "W"}, // Ẉ
            { new int[] { 0x175 }, "w"}, // ŵ
            { new int[] { 0x1E81 }, "w"}, // ẁ
            { new int[] { 0x1E83 }, "w"}, // ẃ
            { new int[] { 0x1E85 }, "w"}, // ẅ
            { new int[] { 0x1E87 }, "w"}, // ẇ
            { new int[] { 0x1E89 }, "w"}, // ẉ
            { new int[] { 0x1E8A }, "X"}, // Ẋ
            { new int[] { 0x1E8C }, "X"}, // Ẍ
            { new int[] { 0x1E8B }, "x"}, // ẋ
            { new int[] { 0x1E8D }, "x"}, // ẍ
            { new int[] { 0x176 }, "Y"}, // Ŷ
            { new int[] { 0x178 }, "Y"}, // Ÿ
            { new int[] { 0x232 }, "Y"}, // Ȳ
            { new int[] { 0x1E8E }, "Y"}, // Ẏ
            { new int[] { 0x177 }, "y"}, // ŷ
            { new int[] { 0x233 }, "y"}, // ȳ
            { new int[] { 0x1E8F }, "y"}, // ẏ
            { new int[] { 0x1E90 }, "Z"}, // Ẑ
            { new int[] { 0x1E92 }, "Z"}, // Ẓ
            { new int[] { 0x1E94 }, "Z"}, // Ẕ
            { new int[] { 0x1E91 }, "z"}, // ẑ
            { new int[] { 0x1E93 }, "z"}, // ẓ
            { new int[] { 0x1E95 }, "z"}, // ẕ
        };
    }
}
